# PRESENT_PERFECT_QUIZ = [
#     # --- LEVEL: BEGINNER (Have/Has + V3) ---
#     {"q": "I ___ my homework already.", "o": ["have finished", "has finished", "finished", "finish"], "c": 0},
#     {"q": "She ___ to Paris twice.", "o": ["have been", "is been", "has been", "was"], "c": 2},
#     {"q": "We ___ that movie before.", "o": ["see", "have seen", "has seen", "saw"], "c": 1},
#     {"q": "They ___ lunch yet.", "o": ["haven't had", "hasn't had", "didn't have", "not had"], "c": 0},
#     {"q": "He ___ his keys again!", "o": ["has lost", "have lost", "is lost", "lose"], "c": 0},
#     {"q": "___ you ever eaten sushi?", "o": ["Has", "Did", "Have", "Are"], "c": 2},
#     {"q": "The cat ___ all the milk.", "o": ["have drunk", "has drunk", "drunk", "drinks"], "c": 1},
#     {"q": "It ___ raining, so we can go out.", "o": ["stops", "has stopped", "have stopped", "is stop"], "c": 1},
#     {"q": "I ___ never been to America.", "o": ["am", "did", "have", "has"], "c": 2},
#     {"q": "My parents ___ just arrived.", "o": ["has", "have", "are", "did"], "c": 1},
#     {"q": "She ___ not called me yet.", "o": ["has", "have", "is", "did"], "c": 0},
#     {"q": "We ___ lived here for ten years.", "o": ["has", "did", "have", "are"], "c": 2},
#     {"q": "Who ___ broken the window?", "o": ["have", "did", "has", "is"], "c": 2},
#     {"q": "I ___ bought a new car.", "o": ["has", "am", "have", "was"], "c": 2},
#     {"q": "They ___ known each other since childhood.", "o": ["have", "has", "are", "did"], "c": 0},
#     {"q": "He ___ already cleaned his room.", "o": ["is", "has", "have", "was"], "c": 1},
#     {"q": "___ she finished her project?", "o": ["Have", "Has", "Did", "Does"], "c": 1},
#     {"q": "You ___ grown so much!", "o": ["have", "has", "is", "are"], "c": 0},
#     {"q": "The bus ___ just left.", "o": ["have", "is", "has", "did"], "c": 2},
#     {"q": "I ___ forgotten your name.", "o": ["has", "have", "am", "did"], "c": 1},
#
#     # --- LEVEL: ELEMENTARY (Ever, Never, Yet, Already) ---
#     {"q": "Have you ___ ridden a horse?", "o": ["never", "ever", "yet", "already"], "c": 1},
#     {"q": "I haven't seen that play ___.", "o": ["already", "just", "yet", "ever"], "c": 2},
#     {"q": "She has ___ sent the email.", "o": ["yet", "already", "ever", "never"], "c": 1},
#     {"q": "We have ___ been to the zoo.", "o": ["ever", "never", "yet", "already"], "c": 1},
#     {"q": "Has the postman come ___?", "o": ["just", "ever", "already", "yet"], "c": 3},
#     {"q": "I've ___ seen a ghost!", "o": ["yet", "ever", "never", "already"], "c": 2},
#     {"q": "They have ___ finished the test.", "o": ["just", "yet", "ever", "never"], "c": 0},
#     {"q": "Have they ___ to Italy?", "o": ["be", "been", "go", "gone"], "c": 1},
#     {"q": "He has ___ lived in London.", "o": ["ever", "yet", "already", "just"], "c": 2},
#     {"q": "I haven't finished my coffee ___.", "o": ["just", "yet", "already", "ever"], "c": 1},
#
#     # --- LEVEL: INTERMEDIATE (For vs Since) ---
#     {"q": "I've worked here ___ 2015.", "o": ["for", "since", "from", "during"], "c": 1},
#     {"q": "They have been married ___ fifty years.", "o": ["since", "for", "ago", "during"], "c": 1},
#     {"q": "She hasn't eaten anything ___ yesterday.", "o": ["for", "since", "until", "from"], "c": 1},
#     {"q": "We've been friends ___ a long time.", "o": ["since", "for", "from", "ago"], "c": 1},
#     {"q": "It hasn't snowed ___ last winter.", "o": ["for", "since", "from", "during"], "c": 1},
#     {"q": "I haven't seen him ___ ages.", "o": ["since", "for", "from", "during"], "c": 1},
#     {"q": "He's been ill ___ three days.", "o": ["since", "for", "ago", "during"], "c": 1},
#     {"q": "We've lived in this house ___ I was born.", "o": ["for", "since", "from", "until"], "c": 1},
#     {"q": "She's been a teacher ___ ten years.", "o": ["since", "for", "ago", "during"], "c": 1},
#     {"q": "I've known her ___ we were at school.", "o": ["for", "since", "from", "ago"], "c": 1},
#
#     # --- Gone vs Been ---
#     {"q": "Where is Tom? He has ___ to the shop.", "o": ["been", "gone", "went", "go"], "c": 1},
#     {"q": "I've ___ to Spain three times.", "o": ["gone", "been", "went", "go"], "c": 1},
#     {"q": "She's not here. She has ___ to the doctor.", "o": ["been", "gone", "goes", "go"], "c": 1},
#     {"q": "Have you ever ___ to a concert?", "o": ["gone", "been", "went", "go"], "c": 1},
#     {"q": "They aren't at home. They've ___ on holiday.", "o": ["been", "gone", "went", "go"], "c": 1},
#     {"q": "I have ___ to the supermarket, the fridge is full now.", "o": ["gone", "been", "went", "go"], "c": 1},
#     {"q": "My sister has ___ to Italy for a year. She lives there now.", "o": ["been", "gone", "went", "go"], "c": 1},
#     {"q": "I've ___ to the bank, so I have some money.", "o": ["gone", "been", "went", "go"], "c": 1},
#     {"q": "He's ___ to the gym. He'll be back in an hour.", "o": ["been", "gone", "went", "go"], "c": 1},
#     {"q": "We've ___ to that new restaurant. It's great!", "o": ["gone", "been", "went", "go"], "c": 1},
#
#     # --- Mixed Practice (201-250) ---
#     {"q": "I ___ (buy) a new pair of shoes.", "o": ["has bought", "have bought", "bought", "buyed"], "c": 1},
#     {"q": "The rain ___ (stop) yet.", "o": ["hasn't stopped", "haven't stopped", "didn't stop", "not stopped"], "c": 0},
#     {"q": "___ you ___ (see) my glasses?", "o": ["Has / seen", "Have / seen", "Did / saw", "Have / saw"], "c": 1},
#     {"q": "Mary ___ (lose) her passport.", "o": ["has lost", "have lost", "lost", "is lost"], "c": 0},
#     {"q": "We ___ (not / meet) him before.", "o": ["hasn't met", "haven't met", "didn't meet", "not met"], "c": 1},
#     {"q": "___ it ___ (start) to snow?", "o": ["Have / started", "Has / started", "Did / started", "Is / starting"], "c": 1},
#     {"q": "I ___ (never / try) Chinese food.", "o": ["has never tried", "have never tried", "never tried", "am never tried"], "c": 1},
#     {"q": "You ___ (make) a mistake.", "o": ["has made", "have made", "made", "maked"], "c": 1},
#     {"q": "The kids ___ (go) to bed.", "o": ["has gone", "have gone", "gone", "went"], "c": 1},
#     {"q": "___ he ___ (ever / win) a trophy?", "o": ["Has / won", "Have / won", "Did / win", "Has / winned"], "c": 0},
#     {"q": "I ___ (already / hear) the news.", "o": ["have already heard", "has already heard", "already heard", "have already hear"], "c": 0},
#     {"q": "She ___ (not / arrive) yet.", "o": ["haven't arrived", "hasn't arrived", "didn't arrive", "not arrived"], "c": 1},
#     {"q": "We ___ (be) busy all day.", "o": ["have been", "has been", "were", "are been"], "c": 0},
#     {"q": "___ you ___ (read) this book?", "o": ["Have / read", "Has / read", "Did / read", "Have / red"], "c": 0},
#     {"q": "They ___ (write) five letters today.", "o": ["has written", "have written", "wrote", "written"], "c": 1},
#     {"q": "He ___ (break) his leg.", "o": ["have broken", "has broken", "broke", "is broken"], "c": 1},
#     {"q": "I ___ (know) him for years.", "o": ["has known", "have known", "knew", "knowed"], "c": 1},
#     {"q": "The birds ___ (fly) away.", "o": ["has flown", "have flown", "flew", "flown"], "c": 1},
#     {"q": "___ she ___ (find) a job?", "o": ["Have / found", "Has / found", "Did / found", "Has / find"], "c": 1},
#     {"q": "It ___ (be) a long time.", "o": ["have been", "has been", "was", "is been"], "c": 1},
#
#     # --- Advanced & Common Errors ---
#     {"q": "I ___ (live) in London since 2010.", "o": ["live", "lived", "have lived", "am living"], "c": 2},
#     {"q": "She ___ (not / see) her sister lately.", "o": ["didn't see", "haven't seen", "hasn't seen", "not saw"], "c": 2},
#     {"q": "How long ___ you ___ (have) this car?", "o": ["did / have", "have / had", "has / had", "do / have"], "c": 1},
#     {"q": "This is the best cake I ___ (ever / eat).", "o": ["ever ate", "have ever eaten", "has ever eaten", "ever eaten"], "c": 1},
#     {"q": "I ___ (not / see) him today.", "o": ["haven't seen", "hasn't seen", "didn't see", "not saw"], "c": 0},
#     {"q": "___ you ___ (finish) yet?", "o": ["Did / finish", "Have / finished", "Has / finished", "Are / finished"], "c": 1},
#     {"q": "Everything ___ (be) fine so far.", "o": ["have been", "has been", "was", "is being"], "c": 1},
#     {"q": "We ___ (not / visit) them this week.", "o": ["didn't visit", "haven't visited", "hasn't visited", "not visit"], "c": 1},
#     {"q": "He ___ (become) very famous.", "o": ["has become", "have become", "became", "becomes"], "c": 0},
#     {"q": "I ___ (tell) you three times!", "o": ["has told", "have told", "told", "telled"], "c": 1},
#     {"q": "She ___ (forget) her umbrella.", "o": ["have forgotten", "has forgotten", "forgot", "forgotten"], "c": 1},
#     {"q": "___ you ___ (hear) from him lately?", "o": ["Did / hear", "Have / heard", "Has / heard", "Do / hear"], "c": 1},
#     {"q": "The prices ___ (go) up recently.", "o": ["has gone", "have gone", "went", "go up"], "c": 1},
#     {"q": "I ___ (just / wake) up.", "o": ["has just woken", "have just woken", "just woke", "have just waked"], "c": 1},
#     {"q": "He ___ (never / speak) to me.", "o": ["has never spoken", "have never spoken", "never spoke", "never speaks"], "c": 0},
#     {"q": "We ___ (win) the game!", "o": ["has won", "have won", "won", "win"], "c": 1},
#     {"q": "___ you ___ (do) the washing up?", "o": ["Have / done", "Has / done", "Did / done", "Do / done"], "c": 0},
#     {"q": "She ___ (lose) a lot of weight.", "o": ["have lost", "has lost", "lost", "is losing"], "c": 1},
#     {"q": "I ___ (not / read) the newspaper today.", "o": ["didn't read", "hasn't read", "haven't read", "not read"], "c": 2},
#     {"q": "They ___ (travel) all over the world.", "o": ["has travelled", "have travelled", "travelled", "are travelled"], "c": 1},
#     {"q": "___ he ___ (tell) you the truth?", "o": ["Have / told", "Has / told", "Did / tell", "Has / tell"], "c": 1},
#     {"q": "I ___ (make) some coffee. Do you want some?", "o": ["has made", "have made", "made", "am making"], "c": 1},
#     {"q": "She ___ (be) to the dentist twice this month.", "o": ["have been", "has been", "was", "is been"], "c": 1},
#     {"q": "___ you ___ (see) my phone anywhere?", "o": ["Did / see", "Have / seen", "Has / seen", "Have / saw"], "c": 1},
#     {"q": "We ___ (just / finish) our dinner.", "o": ["has just finished", "have just finished", "just finished", "finish"], "c": 1},
#     {"q": "He ___ (work) in that company for a long time.", "o": ["works", "worked", "has worked", "have worked"], "c": 2},
#     {"q": "I ___ (never / be) so happy.", "o": ["has never been", "have never been", "was never", "am never"], "c": 1},
#     {"q": "___ they ___ (send) the invitation?", "o": ["Have / sent", "Has / sent", "Did / send", "Have / send"], "c": 0},
#     {"q": "It ___ (not / rain) for weeks.", "o": ["haven't rained", "hasn't rained", "didn't rain", "not rained"], "c": 1},
#     {"q": "You ___ (do) a great job!", "o": ["has done", "have done", "did", "done"], "c": 1},
# # PRESENT_PERFECT_QUIZ davomi (101 - 200)
#     # --- Irregular Verbs (V3) Focus ---
#     {"q": "I ___ (write) a poem for her birthday.", "o": ["have written", "has written", "wrote", "have wrote"], "c": 0},
#     {"q": "She ___ (break) her favorite vase.", "o": ["has broke", "have broken", "has broken", "is broken"], "c": 2},
#     {"q": "We ___ (bring) some snacks for the party.", "o": ["have brought", "has brought", "brought", "have bringed"], "c": 0},
#     {"q": "The birds ___ (fly) south for the winter.", "o": ["has flown", "have flown", "flew", "flown"], "c": 1},
#     {"q": "I ___ (know) him since we were kids.", "o": ["have known", "has known", "knew", "knowed"], "c": 0},
#     {"q": "He ___ (forget) to lock the door.", "o": ["have forgotten", "has forgotten", "forgot", "forgotten"], "c": 1},
#     {"q": "They ___ (steal) my bicycle!", "o": ["has stolen", "have stolen", "stole", "stealed"], "c": 1},
#     {"q": "You ___ (drink) all the orange juice.", "o": ["have drunk", "has drunk", "drank", "drunk"], "c": 0},
#     {"q": "She ___ (sing) that song before.", "o": ["has sung", "have sung", "sang", "sung"], "c": 0},
#     {"q": "We ___ (build) a new house.", "o": ["has built", "have built", "builded", "built"], "c": 1},
#
#     # --- Questions & Negatives ---
#     {"q": "___ you ___ (see) the new Batman movie?", "o": ["Has / seen", "Have / seen", "Did / saw", "Are / seen"], "c": 1},
#     {"q": "___ she ___ (finish) the report yet?", "o": ["Has / finished", "Have / finished", "Did / finish", "Does / finish"], "c": 0},
#     {"q": "They ___ (not / pay) the electricity bill.", "o": ["hasn't paid", "haven't paid", "didn't pay", "not paid"], "c": 1},
#     {"q": "I ___ (not / tell) anyone your secret.", "o": ["hasn't told", "haven't told", "didn't tell", "not told"], "c": 1},
#     {"q": "___ the train ___ (leave) the station?", "o": ["Has / left", "Have / left", "Did / leave", "Is / left"], "c": 0},
#     {"q": "We ___ (not / hear) from them lately.", "o": ["hasn't heard", "haven't heard", "didn't hear", "not heard"], "c": 1},
#     {"q": "Why ___ you ___ (not / eat) your dinner?", "o": ["has / eaten", "have / eaten", "did / eat", "haven't / eaten"], "c": 1},
#     {"q": "___ he ___ (ever / fly) a plane?", "o": ["Has / flown", "Have / flown", "Did / fly", "Is / flying"], "c": 0},
#     {"q": "I ___ (not / buy) the tickets yet.", "o": ["hasn't bought", "haven't bought", "didn't buy", "not bought"], "c": 1},
#     {"q": "___ you ___ (wash) your hands?", "o": ["Has / washed", "Have / washed", "Did / wash", "Are / washed"], "c": 1},
#
#     # --- For vs Since (Deep Dive) ---
#     {"q": "I haven't seen her ___ last Tuesday.", "o": ["for", "since", "from", "ago"], "c": 1},
#     {"q": "He has lived in Japan ___ five years.", "o": ["since", "for", "ago", "during"], "c": 1},
#     {"q": "We've been waiting here ___ 9 o'clock.", "o": ["for", "since", "until", "from"], "c": 1},
#     {"q": "They've been married ___ a long time.", "o": ["since", "for", "from", "ago"], "c": 1},
#     {"q": "She hasn't called me ___ she left.", "o": ["for", "since", "until", "from"], "c": 1},
#     {"q": "I've had this watch ___ Christmas.", "o": ["for", "since", "from", "ago"], "c": 1},
#     {"q": "It has been very hot ___ two weeks.", "o": ["since", "for", "ago", "during"], "c": 1},
#     {"q": "He's been a doctor ___ 2010.", "o": ["for", "since", "from", "ago"], "c": 1},
#     {"q": "I haven't been to the cinema ___ months.", "o": ["since", "for", "ago", "during"], "c": 1},
#     {"q": "We haven't spoken ___ the argument.", "o": ["for", "since", "until", "from"], "c": 1},
#
#     # --- Just, Already, Yet ---
#     {"q": "I've ___ finished my lunch. I'm full.", "o": ["yet", "already", "just", "ever"], "c": 2},
#     {"q": "Have you seen the boss ___?", "o": ["just", "already", "yet", "never"], "c": 2},
#     {"q": "She's ___ sent the invitations. She did it yesterday.", "o": ["yet", "just", "already", "ever"], "c": 2},
#     {"q": "The plane has ___ landed.", "o": ["yet", "just", "ever", "never"], "c": 1},
#     {"q": "I haven't done my homework ___.", "o": ["already", "just", "yet", "ever"], "c": 2},
#     {"q": "We've ___ seen this movie twice.", "o": ["yet", "already", "ever", "never"], "c": 1},
#     {"q": "Has he called you back ___?", "o": ["just", "already", "yet", "ever"], "c": 2},
#     {"q": "I've ___ heard the news. It's shocking!", "o": ["yet", "ever", "just", "already"], "c": 2},
#     {"q": "They haven't arrived ___.", "o": ["already", "just", "yet", "ever"], "c": 2},
#     {"q": "She has ___ left the office.", "o": ["yet", "just", "ever", "already"], "c": 1},
#
#     # --- Gone vs Been (Revisited) ---
#     {"q": "Where's Sarah? She's ___ to the park.", "o": ["been", "gone", "went", "go"], "c": 1},
#     {"q": "I've ___ to the park today. It was beautiful.", "o": ["gone", "been", "went", "go"], "c": 1},
#     {"q": "The kids have ___ to school. They'll be back at 4.", "o": ["been", "gone", "went", "go"], "c": 1},
#     {"q": "Have you ever ___ to London?", "o": ["gone", "been", "went", "go"], "c": 1},
#     {"q": "He isn't here. He's ___ to the post office.", "o": ["been", "gone", "went", "go"], "c": 1},
#     {"q": "We've ___ to that new cafe. The coffee is great.", "o": ["gone", "been", "went", "go"], "c": 1},
#     {"q": "My parents have ___ to the cinema. They are watching a movie now.", "o": ["been", "gone", "went", "go"], "c": 1},
#     {"q": "I've ___ to the library to return some books.", "o": ["gone", "been", "went", "go"], "c": 1},
#     {"q": "She has ___ to Paris for her honeymoon. She's there now.", "o": ["been", "gone", "went", "go"], "c": 1},
#     {"q": "Have they ___ to the meeting yet?", "o": ["gone", "been", "went", "go"], "c": 1},
#
#     # --- Mixed Practice ---
#     {"q": "I ___ (lose) my umbrella.", "o": ["has lost", "have lost", "lost", "lose"], "c": 1},
#     {"q": "She ___ (never / eat) snails.", "o": ["has never eaten", "have never eaten", "never ate", "never eats"], "c": 0},
#     {"q": "___ you ___ (be) to the new museum?", "o": ["Has / been", "Have / been", "Did / be", "Are / been"], "c": 1},
#     {"q": "We ___ (not / see) him today.", "o": ["hasn't seen", "haven't seen", "didn't see", "not saw"], "c": 1},
#     {"q": "The sun ___ (not / come) out yet.", "o": ["hasn't come", "haven't come", "didn't come", "not come"], "c": 0},
#     {"q": "___ she ___ (find) her keys?", "o": ["Have / found", "Has / found", "Did / find", "Has / find"], "c": 1},
#     {"q": "They ___ (buy) a new car.", "o": ["has bought", "have bought", "bought", "buyed"], "c": 1},
#     {"q": "I ___ (already / do) the laundry.", "o": ["have already done", "has already done", "already did", "have already did"], "c": 0},
#     {"q": "___ you ___ (ever / meet) a famous person?", "o": ["Has / met", "Have / met", "Did / meet", "Have / meeted"], "c": 1},
#     {"q": "He ___ (not / finish) the book yet.", "o": ["hasn't finished", "haven't finished", "didn't finish", "not finished"], "c": 0},
#     {"q": "We ___ (be) friends for a long time.", "o": ["has been", "have been", "were", "are being"], "c": 1},
#     {"q": "___ it ___ (stop) raining?", "o": ["Have / stopped", "Has / stopped", "Did / stop", "Is / stopped"], "c": 1},
#     {"q": "I ___ (never / try) skiing.", "o": ["has never tried", "have never tried", "never tried", "am never tried"], "c": 1},
#     {"q": "She ___ (already / leave) for the airport.", "o": ["have already left", "has already left", "already left", "has already leave"], "c": 1},
#     {"q": "They ___ (not / receive) the package yet.", "o": ["hasn't received", "haven't received", "didn't receive", "not received"], "c": 1},
#     {"q": "___ you ___ (take) the dog for a walk?", "o": ["Has / taken", "Have / taken", "Did / take", "Have / took"], "c": 1},
#     {"q": "He ___ (work) here since last year.", "o": ["has worked", "have worked", "worked", "is working"], "c": 0},
#     {"q": "I ___ (just / see) a shooting star!", "o": ["has just seen", "have just seen", "just saw", "have just saw"], "c": 1},
#     {"q": "She ___ (not / tell) me the truth.", "o": ["hasn't told", "haven't told", "didn't tell", "not told"], "c": 0},
#     {"q": "___ they ___ (be) to the beach lately?", "o": ["Has / been", "Have / been", "Did / be", "Are / been"], "c": 1},
#     {"q": "I ___ (forget) your phone number.", "o": ["has forgotten", "have forgotten", "forgot", "forgotten"], "c": 1},
#     {"q": "The cat ___ (catch) a mouse.", "o": ["have caught", "has caught", "caught", "has catched"], "c": 1},
#     {"q": "We ___ (not / visit) our grandparents this month.", "o": ["hasn't visited", "haven't visited", "didn't visit", "not visit"], "c": 1},
#     {"q": "___ he ___ (ever / win) a race?", "o": ["Has / won", "Have / won", "Did / win", "Has / winned"], "c": 0},
#     {"q": "I ___ (read) that book three times.", "o": ["has read", "have read", "read", "have red"], "c": 1},
#     {"q": "She ___ (break) her glasses.", "o": ["have broken", "has broken", "broke", "has broke"], "c": 1},
#     {"q": "They ___ (go) to the cinema.", "o": ["has gone", "have gone", "went", "gone"], "c": 1},
#     {"q": "___ you ___ (ever / see) a lion?", "o": ["Has / seen", "Have / seen", "Did / saw", "Have / saw"], "c": 1},
#     {"q": "I ___ (just / buy) a new laptop.", "o": ["has just bought", "have just bought", "just bought", "have just buyed"], "c": 1},
#     {"q": "We ___ (not / eat) at that restaurant yet.", "o": ["hasn't eaten", "haven't eaten", "didn't eat", "not eaten"], "c": 1},
#     {"q": "She ___ (be) a nurse for ten years.", "o": ["has been", "have been", "was", "is being"], "c": 0},
#     {"q": "___ he ___ (do) his homework?", "o": ["Have / done", "Has / done", "Did / do", "Has / did"], "c": 1},
#     {"q": "I ___ (not / hear) that song before.", "o": ["hasn't heard", "haven't heard", "didn't hear", "not heard"], "c": 1},
#     {"q": "They ___ (already / finish) the project.", "o": ["has already finished", "have already finished", "already finished", "have already finish"], "c": 1},
#     {"q": "___ you ___ (ever / be) to New York?", "o": ["Has / been", "Have / been", "Did / be", "Are / been"], "c": 1},
#     {"q": "She ___ (lose) her keys again.", "o": ["have lost", "has lost", "lost", "is losing"], "c": 1},
#     {"q": "We ___ (just / see) a great movie.", "o": ["has just seen", "have just seen", "just saw", "have just saw"], "c": 1},
#     {"q": "I ___ (not / tell) him the news yet.", "o": ["hasn't told", "haven't told", "didn't tell", "not told"], "c": 1},
#     {"q": "___ they ___ (find) a new apartment?", "o": ["Have / found", "Has / found", "Did / find", "Have / find"], "c": 0},
#     {"q": "He ___ (break) his arm.", "o": ["have broken", "has broken", "broke", "has broke"], "c": 1},
# # PRESENT_PERFECT_QUIZ davomi (201 - 300)
#     # --- How long...? and Durations ---
#     {"q": "How long ___ you ___ (know) your best friend?", "o": ["did / know", "have / known", "has / known", "do / know"], "c": 1},
#     {"q": "How long ___ she ___ (be) a doctor?", "o": ["has / been", "have / been", "is / being", "did / be"], "c": 0},
#     {"q": "How long ___ they ___ (live) in this city?", "o": ["did / live", "have / lived", "has / lived", "do / live"], "c": 1},
#     {"q": "I ___ (have) this watch for twenty years.", "o": ["has had", "have had", "had", "have have"], "c": 1},
#     {"q": "We ___ (not / see) a movie for months.", "o": ["hasn't seen", "haven't seen", "didn't see", "not seen"], "c": 1},
#     {"q": "He ___ (be) in the hospital since Monday.", "o": ["has been", "have been", "was", "is being"], "c": 0},
#     {"q": "___ you ___ (be) awake for a long time?", "o": ["Has / been", "Have / been", "Did / be", "Are / been"], "c": 1},
#     {"q": "She ___ (work) here since she graduated.", "o": ["has worked", "have worked", "worked", "is working"], "c": 0},
#     {"q": "They ___ (not / eat) meat for five years.", "o": ["hasn't eaten", "haven't eaten", "didn't eat", "not eaten"], "c": 1},
#     {"q": "My dog ___ (be) part of our family for a decade.", "o": ["have been", "has been", "was", "is being"], "c": 1},
#
#     # --- Ever / Never / Before ---
#     {"q": "This is the first time I ___ (ever / see) a whale.", "o": ["ever saw", "have ever seen", "has ever seen", "ever seen"], "c": 1},
#     {"q": "I've ___ (never / be) so embarrassed in my life!", "o": ["never been", "has never been", "never was", "never am"], "c": 0},
#     {"q": "___ you ___ (ever / try) bungee jumping?", "o": ["Did / try", "Have / tried", "Has / tried", "Are / tried"], "c": 1},
#     {"q": "He has ___ (never / taste) such a good pizza.", "o": ["never tasted", "ever tasted", "never taste", "never tastes"], "c": 0},
#     {"q": "We ___ (not / be) to this restaurant before.", "o": ["hasn't been", "haven't been", "didn't be", "not been"], "c": 1},
#     {"q": "___ she ___ (ever / meet) the president?", "o": ["Have / met", "Has / met", "Did / meet", "Has / meet"], "c": 1},
#     {"q": "I've ___ (already / read) that book twice.", "o": ["already read", "already red", "have already read", "already reading"], "c": 0},
#     {"q": "They have ___ (never / hear) of this place.", "o": ["never heard", "ever heard", "never hear", "never hears"], "c": 0},
#     {"q": "Have you ___ (ever / feel) like this before?", "o": ["ever feel", "ever felt", "never felt", "ever feels"], "c": 1},
#     {"q": "I've ___ (never / travel) by plane.", "o": ["never travelled", "ever travelled", "never travel", "never travels"], "c": 0},
#
#     # --- Present Perfect vs Simple Past (Context) ---
#     {"q": "I ___ (lose) my key. I can't find it now.", "o": ["lost", "have lost", "has lost", "am losing"], "c": 1},
#     {"q": "She ___ (break) her leg last week.", "o": ["has broken", "broke", "have broken", "is breaking"], "c": 1}, # Note: This is Past Simple
#     {"q": "Somebody ___ (steal) my phone today!", "o": ["stole", "has stolen", "have stolen", "steals"], "c": 1},
#     {"q": "I ___ (not / see) him this morning.", "o": ["didn't see", "haven't seen", "hasn't seen", "not saw"], "c": 1},
#     {"q": "The mail ___ (arrive) just now.", "o": ["arrived", "has arrived", "have arrived", "arriving"], "c": 1},
#     {"q": "___ you ___ (finish) your dinner yet?", "o": ["Did / finish", "Have / finished", "Has / finished", "Do / finish"], "c": 1},
#     {"q": "We ___ (buy) a new car recently.", "o": ["bought", "have bought", "has bought", "buyed"], "c": 1},
#     {"q": "Everything ___ (be) easy so far.", "o": ["was", "has been", "have been", "is being"], "c": 1},
#     {"q": "I ___ (read) 50 pages of this book today.", "o": ["read", "have read", "has read", "red"], "c": 1},
#     {"q": "She ___ (not / call) me since yesterday.", "o": ["didn't call", "hasn't called", "haven't called", "not called"], "c": 1},
#
#     # --- Just / Already / Yet Mixed ---
#     {"q": "The bus has ___ left.", "o": ["yet", "already", "ever", "never"], "c": 1},
#     {"q": "Has the movie started ___?", "o": ["just", "already", "yet", "ever"], "c": 2},
#     {"q": "I have ___ cleaned the floor, don't walk on it!", "o": ["yet", "ever", "just", "never"], "c": 2},
#     {"q": "We haven't decided where to go ___.", "o": ["already", "just", "yet", "ever"], "c": 2},
#     {"q": "They have ___ paid for the tickets.", "o": ["yet", "just", "already", "ever"], "c": 2},
#     {"q": "Has he finished his work ___?", "o": ["already", "just", "yet", "ever"], "c": 2},
#     {"q": "I've ___ seen that guy before.", "o": ["yet", "ever", "already", "never"], "c": 2},
#     {"q": "The coffee is hot, I've ___ made it.", "o": ["yet", "ever", "just", "never"], "c": 2},
#     {"q": "She hasn't spoken to me ___.", "o": ["already", "just", "yet", "ever"], "c": 2},
#     {"q": "We've ___ eaten breakfast.", "o": ["yet", "ever", "already", "never"], "c": 2},
#
#     # --- Gone vs Been Focus ---
#     {"q": "Tom is away. He has ___ to Italy.", "o": ["been", "gone", "went", "go"], "c": 1},
#     {"q": "I've ___ to Italy many times.", "o": ["been", "gone", "went", "go"], "c": 0},
#     {"q": "Where have you ___? I was looking for you.", "o": ["been", "gone", "went", "go"], "c": 0},
#     {"q": "She has ___ to the library. She'll be back soon.", "o": ["been", "gone", "went", "go"], "c": 1},
#     {"q": "Have you ever ___ to a football match?", "o": ["been", "gone", "went", "go"], "c": 0},
#     {"q": "My sister isn't here. She's ___ shopping.", "o": ["been", "gone", "went", "go"], "c": 1},
#     {"q": "I have ___ to the shop, look what I bought!", "o": ["been", "gone", "went", "go"], "c": 0},
#     {"q": "They've ___ to Paris. They are living there now.", "o": ["been", "gone", "went", "go"], "c": 1},
#     {"q": "He's ___ to the doctor. He should be back in an hour.", "o": ["been", "gone", "went", "go"], "c": 1},
#     {"q": "We've ___ to that new gym. It's very clean.", "o": ["been", "gone", "went", "go"], "c": 0},
#
#     # --- Mixed Finale (251-300) ---
#     {"q": "I ___ (pay) for the coffee.", "o": ["has paid", "have paid", "paid", "payed"], "c": 1},
#     {"q": "The sun ___ (not / set) yet.", "o": ["hasn't set", "haven't set", "didn't set", "not set"], "c": 0},
#     {"q": "___ you ___ (bring) the umbrella?", "o": ["Has / brought", "Have / brought", "Did / bring", "Have / bringed"], "c": 1},
#     {"q": "She ___ (lose) her ring.", "o": ["has lost", "have lost", "lost", "is losing"], "c": 0},
#     {"q": "They ___ (not / arrive) home yet.", "o": ["hasn't arrived", "haven't arrived", "didn't arrive", "not arrived"], "c": 1},
#     {"q": "___ he ___ (ever / ride) a motorcycle?", "o": ["Has / ridden", "Have / ridden", "Did / ride", "Has / ride"], "c": 0},
#     {"q": "I ___ (never / see) such a big house.", "o": ["has never seen", "have never seen", "never saw", "am never seen"], "c": 1},
#     {"q": "We ___ (buy) some new clothes.", "o": ["has bought", "have bought", "bought", "buyed"], "c": 1},
#     {"q": "___ you ___ (send) the email?", "o": ["Has / sent", "Have / sent", "Did / send", "Have / send"], "c": 1},
#     {"q": "He ___ (break) the window.", "o": ["have broken", "has broken", "broke", "is broken"], "c": 1},
#     {"q": "I ___ (know) her for a long time.", "o": ["has known", "have known", "knew", "knowed"], "c": 1},
#     {"q": "The water ___ (freeze).", "o": ["has frozen", "have frozen", "froze", "frozen"], "c": 0},
#     {"q": "___ she ___ (find) her phone?", "o": ["Have / found", "Has / found", "Did / find", "Has / find"], "c": 1},
#     {"q": "We ___ (not / meet) before.", "o": ["hasn't met", "haven't met", "didn't meet", "not met"], "c": 1},
#     {"q": "The cat ___ (hide) under the bed.", "o": ["has hidden", "have hidden", "hid", "hidden"], "c": 0},
#     {"q": "___ you ___ (hear) the news?", "o": ["Has / heard", "Have / heard", "Did / hear", "Have / hear"], "c": 1},
#     {"q": "They ___ (not / build) the bridge yet.", "o": ["hasn't built", "haven't built", "didn't build", "not build"], "c": 1},
#     {"q": "He ___ (become) a manager.", "o": ["has become", "have become", "became", "becomes"], "c": 0},
#     {"q": "I ___ (never / be) so tired.", "o": ["has never been", "have never been", "was never", "am never"], "c": 1},
#     {"q": "___ it ___ (start) to rain?", "o": ["Have / started", "Has / started", "Did / start", "Is / starting"], "c": 1},
#     {"q": "I ___ (just / eat) a sandwich.", "o": ["has just eaten", "have just eaten", "just ate", "have just eat"], "c": 1},
#     {"q": "She ___ (forget) her bag.", "o": ["have forgotten", "has forgotten", "forgot", "forgotten"], "c": 1},
#     {"q": "They ___ (not / call) us this week.", "o": ["hasn't called", "haven't called", "didn't call", "not call"], "c": 1},
#     {"q": "___ you ___ (take) your medicine?", "o": ["Has / taken", "Have / taken", "Did / take", "Have / took"], "c": 1},
#     {"q": "We ___ (be) to the zoo three times.", "o": ["has been", "have been", "were", "are been"], "c": 1},
#     {"q": "He ___ (finish) his project finally.", "o": ["have finished", "has finished", "finished", "finish"], "c": 1},
#     {"q": "I ___ (not / see) my brother for years.", "o": ["hasn't seen", "haven't seen", "didn't see", "not seen"], "c": 1},
#     {"q": "___ they ___ (go) out yet?", "o": ["Have / gone", "Has / gone", "Did / go", "Have / go"], "c": 0},
#     {"q": "She ___ (write) a long letter.", "o": ["have written", "has written", "wrote", "written"], "c": 1},
#     {"q": "I ___ (not / drink) any water today.", "o": ["hasn't drunk", "haven't drunk", "didn't drink", "not drink"], "c": 1},
#     {"q": "___ you ___ (ever / fly) in a helicopter?", "o": ["Has / flown", "Have / flown", "Did / fly", "Has / fly"], "c": 1},
#     {"q": "They ___ (already / win) two games.", "o": ["has already won", "have already won", "already won", "have already win"], "c": 1},
#     {"q": "He ___ (lose) his wallet.", "o": ["have lost", "has lost", "lost", "is losing"], "c": 1},
#     {"q": "We ___ (not / meet) the new teacher yet.", "o": ["hasn't met", "haven't met", "didn't meet", "not met"], "c": 1},
#     {"q": "___ she ___ (ever / be) to Spain?", "o": ["Have / been", "Has / been", "Did / be", "Are / been"], "c": 1},
#     {"q": "I ___ (already / do) my hair.", "o": ["have already done", "has already done", "already did", "done"], "c": 0},
#     {"q": "They ___ (just / leave) the building.", "o": ["has just left", "have just left", "just left", "leave"], "c": 1},
#     {"q": "___ you ___ (choose) a gift yet?", "o": ["Have / chosen", "Has / chosen", "Did / choose", "Have / chose"], "c": 0},
#     {"q": "He ___ (never / say) sorry.", "o": ["has never said", "have never said", "never said", "never says"], "c": 0},
#     {"q": "We ___ (finish) all the work!", "o": ["has finished", "have finished", "finished", "finishes"], "c": 1},
# # PRESENT_PERFECT_QUIZ davomi (301 - 400)
#     # --- Irregular Verbs Mastery ---
#     {"q": "I ___ (send) the package this morning.", "o": ["has sent", "have sent", "sent", "have send"], "c": 1},
#     {"q": "She ___ (keep) the secret for years.", "o": ["have kept", "has kept", "kept", "keeped"], "c": 1},
#     {"q": "We ___ (not / spend) any money today.", "o": ["hasn't spent", "haven't spent", "didn't spend", "not spent"], "c": 1},
#     {"q": "The baby ___ (sleep) for three hours.", "o": ["has slept", "have slept", "slept", "is slept"], "c": 0},
#     {"q": "I ___ (tell) him everything I know.", "o": ["has told", "have told", "told", "telled"], "c": 1},
#     {"q": "They ___ (win) the lottery!", "o": ["has won", "have won", "won", "win"], "c": 1},
#     {"q": "He ___ (leave) his hat in the taxi.", "o": ["have left", "has left", "left", "leaved"], "c": 1},
#     {"q": "___ you ___ (find) your glasses yet?", "o": ["Has / found", "Have / found", "Did / find", "Are / found"], "c": 1},
#     {"q": "We ___ (buy) enough food for the week.", "o": ["has bought", "have bought", "bought", "buyed"], "c": 1},
#     {"q": "The sun ___ (rise) already.", "o": ["has risen", "have risen", "rose", "risen"], "c": 0},
#
#     # --- Negative Sentences Focus ---
#     {"q": "I ___ (not / see) that person before.", "o": ["hasn't seen", "haven't seen", "didn't see", "not seen"], "c": 1},
#     {"q": "She ___ (not / finish) her breakfast.", "o": ["haven't finished", "hasn't finished", "didn't finish", "not finish"], "c": 1},
#     {"q": "They ___ (not / call) me since June.", "o": ["hasn't called", "haven't called", "didn't call", "not called"], "c": 1},
#     {"q": "It ___ (not / snow) this winter yet.", "o": ["hasn't snowed", "haven't snowed", "didn't snow", "not snowed"], "c": 0},
#     {"q": "We ___ (not / meet) the manager.", "o": ["hasn't met", "haven't met", "didn't meet", "not met"], "c": 1},
#     {"q": "You ___ (not / do) what I asked.", "o": ["hasn't done", "haven't done", "didn't do", "not done"], "c": 1},
#     {"q": "He ___ (not / be) to the dentist for a year.", "o": ["haven't been", "hasn't been", "wasn't", "is not"], "c": 1},
#     {"q": "I ___ (not / read) the instructions yet.", "o": ["hasn't read", "haven't read", "didn't read", "not read"], "c": 2},
#     {"q": "They ___ (not / pay) the rent.", "o": ["hasn't paid", "haven't paid", "didn't pay", "not paid"], "c": 1},
#     {"q": "She ___ (not / lose) hope.", "o": ["haven't lost", "hasn't lost", "didn't lose", "not lost"], "c": 1},
#
#     # --- Questions & Replies ---
#     {"q": "___ you ___ (ever / play) golf?", "o": ["Did / play", "Have / played", "Has / played", "Are / playing"], "c": 1},
#     {"q": "___ he ___ (just / arrive)?", "o": ["Have / arrived", "Has / arrived", "Did / arrive", "Is / arrived"], "c": 1},
#     {"q": "___ they ___ (be) to the mountains lately?", "o": ["Has / been", "Have / been", "Did / be", "Are / been"], "c": 1},
#     {"q": "___ she ___ (take) her exams yet?", "o": ["Has / taken", "Have / taken", "Did / take", "Does / take"], "c": 0},
#     {"q": "___ you ___ (hear) the news about the accident?", "o": ["Has / heard", "Have / heard", "Did / hear", "Do / hear"], "c": 1},
#     {"q": "___ it ___ (stop) raining?", "o": ["Have / stopped", "Has / stopped", "Did / stop", "Is / stopped"], "c": 1},
#     {"q": "___ you ___ (choose) a name for the baby?", "o": ["Has / chosen", "Have / chosen", "Did / choose", "Are / choosing"], "c": 1},
#     {"q": "___ she ___ (buy) the milk?", "o": ["Have / bought", "Has / bought", "Did / buy", "Has / buy"], "c": 1},
#     {"q": "___ they ___ (finish) the building?", "o": ["Has / finished", "Have / finished", "Did / finish", "Are / finished"], "c": 1},
#     {"q": "___ you ___ (ever / see) a ghost?", "o": ["Has / seen", "Have / seen", "Did / see", "Are / seen"], "c": 1},
#
#     # --- Since / For / How Long ---
#     {"q": "I've been in this office ___ 8:00 AM.", "o": ["for", "since", "during", "until"], "c": 1},
#     {"q": "She's known him ___ ten years.", "o": ["since", "for", "ago", "from"], "c": 1},
#     {"q": "How long ___ you ___ (have) that cold?", "o": ["did / have", "have / had", "has / had", "do / have"], "c": 1},
#     {"q": "They've lived here ___ they got married.", "o": ["for", "since", "until", "from"], "c": 1},
#     {"q": "We haven't seen them ___ a long time.", "o": ["since", "for", "ago", "from"], "c": 1},
#     {"q": "I've had this car ___ 2018.", "o": ["for", "since", "during", "from"], "c": 1},
#     {"q": "He hasn't eaten meat ___ he was a child.", "o": ["for", "since", "until", "from"], "c": 1},
#     {"q": "She's been a nurse ___ she left college.", "o": ["for", "since", "during", "until"], "c": 1},
#     {"q": "We've been friends ___ ages.", "o": ["since", "for", "ago", "from"], "c": 1},
#     {"q": "How long ___ she ___ (study) English?", "o": ["did / study", "has / studied", "have / studied", "does / study"], "c": 1},
#
#     # --- Already / Just / Yet / Never ---
#     {"q": "I have ___ finished. Can I go now?", "o": ["yet", "already", "just", "ever"], "c": 2},
#     {"q": "Has she called you ___?", "o": ["just", "already", "yet", "ever"], "c": 2},
#     {"q": "I've ___ seen that film twice.", "o": ["yet", "ever", "already", "never"], "c": 2},
#     {"q": "They haven't arrived ___.", "o": ["already", "just", "yet", "never"], "c": 2},
#     {"q": "We've ___ eaten dinner.", "o": ["yet", "ever", "already", "never"], "c": 2},
#     {"q": "I've ___ heard such a funny story!", "o": ["never", "ever", "yet", "already"], "c": 0},
#     {"q": "Has the mailman been ___?", "o": ["just", "already", "yet", "ever"], "c": 2},
#     {"q": "She has ___ left the building.", "o": ["yet", "just", "ever", "already"], "c": 1},
#     {"q": "I've ___ known him to be late.", "o": ["never", "ever", "yet", "already"], "c": 0},
#     {"q": "Have they decided ___?", "o": ["just", "already", "yet", "ever"], "c": 2},
#
#     # --- Mixed Practice 1 ---
#     {"q": "I ___ (lose) my passport.", "o": ["has lost", "have lost", "lost", "lose"], "c": 1},
#     {"q": "She ___ (write) three books.", "o": ["have written", "has written", "wrote", "written"], "c": 1},
#     {"q": "We ___ (not / meet) the new neighbor.", "o": ["hasn't met", "haven't met", "didn't meet", "not met"], "c": 1},
#     {"q": "___ you ___ (see) the keys?", "o": ["Has / seen", "Have / seen", "Did / see", "Are / seen"], "c": 1},
#     {"q": "The cat ___ (drink) its milk.", "o": ["have drunk", "has drunk", "drunk", "drank"], "c": 1},
#     {"q": "He ___ (break) his leg.", "o": ["have broken", "has broken", "broke", "is broken"], "c": 1},
#     {"q": "I ___ (never / fly) in a helicopter.", "o": ["has never flown", "have never flown", "never flew", "never fly"], "c": 1},
#     {"q": "They ___ (buy) a house recently.", "o": ["has bought", "have bought", "bought", "buyed"], "c": 1},
#     {"q": "___ she ___ (find) her phone?", "o": ["Have / found", "Has / found", "Did / find", "Has / find"], "c": 1},
#     {"q": "It ___ (not / rain) today.", "o": ["haven't rained", "hasn't rained", "didn't rain", "not rained"], "c": 1},
#
#     # --- Mixed Practice 2 ---
#     {"q": "I ___ (just / take) a shower.", "o": ["has just taken", "have just taken", "just took", "have just took"], "c": 1},
#     {"q": "We ___ (already / see) this movie.", "o": ["have already seen", "has already seen", "already saw", "already seen"], "c": 0},
#     {"q": "She ___ (not / tell) me the truth.", "o": ["hasn't told", "haven't told", "didn't tell", "not told"], "c": 0},
#     {"q": "___ they ___ (finish) the project?", "o": ["Has / finished", "Have / finished", "Did / finish", "Are / finished"], "c": 1},
#     {"q": "He ___ (be) to Paris three times.", "o": ["have been", "has been", "was", "is been"], "c": 1},
#     {"q": "I ___ (forget) her name.", "o": ["has forgotten", "have forgotten", "forgot", "forgotten"], "c": 1},
#     {"q": "The birds ___ (fly) away.", "o": ["has flown", "have flown", "flew", "flown"], "c": 1},
#     {"q": "___ you ___ (read) the newspaper?", "o": ["Has / read", "Have / read", "Did / read", "Have / red"], "c": 1},
#     {"q": "We ___ (know) him for years.", "o": ["has known", "have known", "knew", "knowed"], "c": 1},
#     {"q": "She ___ (lose) her ring.", "o": ["have lost", "has lost", "lost", "is losing"], "c": 1},
#
#     # --- Mixed Practice 3 ---
#     {"q": "I ___ (pay) the bill.", "o": ["has paid", "have paid", "paid", "payed"], "c": 1},
#     {"q": "The kids ___ (go) to bed.", "o": ["has gone", "have gone", "gone", "went"], "c": 1},
#     {"q": "___ he ___ (ever / eat) sushi?", "o": ["Has / eaten", "Have / eaten", "Did / eat", "Has / eat"], "c": 0},
#     {"q": "I ___ (not / hear) that song before.", "o": ["hasn't heard", "haven't heard", "didn't hear", "not heard"], "c": 1},
#     {"q": "We ___ (just / start) the lesson.", "o": ["has just started", "have just started", "just started", "started"], "c": 1},
#     {"q": "She ___ (already / leave).", "o": ["have already left", "has already left", "already left", "leave"], "c": 1},
#     {"q": "___ they ___ (find) a new job?", "o": ["Have / found", "Has / found", "Did / find", "Have / find"], "c": 0},
#     {"q": "He ___ (break) the window.", "o": ["have broken", "has broken", "broke", "broken"], "c": 1},
#     {"q": "I ___ (never / be) to London.", "o": ["has never been", "have never been", "never was", "never am"], "c": 1},
#     {"q": "___ you ___ (see) my glasses?", "o": ["Has / seen", "Have / seen", "Did / see", "Have / saw"], "c": 1},
#
#     # --- Finale ---
#     {"q": "I ___ (finish) the task.", "o": ["has finished", "have finished", "finished", "finish"], "c": 1},
#     {"q": "She ___ (forget) her umbrella again.", "o": ["have forgotten", "has forgotten", "forgot", "forgotten"], "c": 1},
#     {"q": "We ___ (not / receive) the letter yet.", "o": ["hasn't received", "haven't received", "didn't receive", "not received"], "c": 1},
#     {"q": "___ they ___ (win) the game?", "o": ["Has / won", "Have / won", "Did / win", "Are / winning"], "c": 1},
#     {"q": "He ___ (just / call) me.", "o": ["has just called", "have just called", "just called", "calls"], "c": 0},
#     {"q": "I ___ (already / do) it.", "o": ["have already done", "has already done", "already did", "done"], "c": 0},
#     {"q": "She ___ (never / try) Italian food.", "o": ["has never tried", "have never tried", "never tried", "never try"], "c": 1},
#     {"q": "___ you ___ (ever / see) a whale?", "o": ["Has / seen", "Have / seen", "Did / saw", "Are / seen"], "c": 1},
#     {"q": "They ___ (leave) the party.", "o": ["has left", "have left", "left", "leaved"], "c": 1},
#     {"q": "I ___ (lose) my way.", "o": ["has lost", "have lost", "lost", "lose"], "c": 1},
#     {"q": "She ___ (just / buy) a new bag.", "o": ["has just bought", "have just bought", "just bought", "bought"], "c": 0},
#     {"q": "We ___ (not / hear) anything yet.", "o": ["hasn't heard", "haven't heard", "didn't hear", "not heard"], "c": 1},
#     {"q": "___ he ___ (finish) his work?", "o": ["Have / finished", "Has / finished", "Did / finish", "Does / finish"], "c": 1},
#     {"q": "I ___ (be) to the doctor.", "o": ["has been", "have been", "was", "is been"], "c": 1},
#     {"q": "They ___ (just / arrived).", "o": ["has just arrived", "have just arrived", "just arrived", "arrive"], "c": 1},
#     {"q": "___ you ___ (choose) a gift?", "o": ["Have / chosen", "Has / chosen", "Did / choose", "Are / chose"], "c": 0},
#     {"q": "She ___ (not / see) him lately.", "o": ["hasn't seen", "haven't seen", "didn't see", "not saw"], "c": 0},
#     {"q": "We ___ (already / eat) dinner.", "o": ["have already eaten", "has already eaten", "already ate", "already eat"], "c": 0},
#     {"q": "I ___ (never / tell) a lie.", "o": ["has never told", "have never told", "never told", "never tell"], "c": 1},
#     {"q": "___ it ___ (stop) snowing?", "o": ["Have / stopped", "Has / stopped", "Did / stop", "Is / stopped"], "c": 1}
# ]
#
#
