PRESENT_SIMPLE_QUIZ = [
    # --- LEVEL: BEGINNER (To be, simple verbs) ---
    {"q": "I ___ a student.", "o": ["am", "is", "are", "be"], "c": 0},
    {"q": "They ___ from Spain.", "o": ["is", "are", "am", "be"], "c": 1},
    {"q": "She ___ a big house.", "o": ["have", "has", "is having", "having"], "c": 1},
    {"q": "We ___ happy today.", "o": ["am", "is", "are", "been"], "c": 2},
    {"q": "It ___ a sunny day.", "o": ["am", "is", "are", "be"], "c": 1},
    {"q": "You ___ my best friend.", "o": ["is", "am", "are", "be"], "c": 2},
    {"q": "I ___ not hungry.", "o": ["am", "is", "are", "be"], "c": 0},
    {"q": "___ he your brother?", "o": ["Are", "Is", "Am", "Do"], "c": 1},
    {"q": "They ___ football on Saturdays.", "o": ["plays", "play", "playing", "played"], "c": 1},
    {"q": "The cat ___ on the sofa.", "o": ["sleep", "sleeps", "is sleep", "sleeping"], "c": 1},
    {"q": "I ___ breakfast at 7 AM.", "o": ["eat", "eats", "eating", "ate"], "c": 0},
    {"q": "My mom ___ delicious cakes.", "o": ["make", "makes", "making", "made"], "c": 1},
    {"q": "We ___ to school by bus.", "o": ["goes", "go", "going", "gone"], "c": 1},
    {"q": "Do you ___ English?", "o": ["speak", "speaks", "speaking", "spoke"], "c": 0},
    {"q": "He ___ not like apples.", "o": ["do", "does", "is", "not"], "c": 1},
    {"q": "___ they live in Tashkent?", "o": ["Does", "Do", "Are", "Is"], "c": 1},
    {"q": "I ___ my room every day.", "o": ["clean", "cleans", "cleaning", "cleaned"], "c": 0},
    {"q": "Birds ___ in the sky.", "o": ["fly", "flies", "flying", "flew"], "c": 0},
    {"q": "The sun ___ in the morning.", "o": ["shine", "shines", "shining", "shone"], "c": 1},
    {"q": "My father ___ a car.", "o": ["drive", "drives", "driving", "drove"], "c": 1},
    {"q": "We ___ movies on Friday.", "o": ["watch", "watches", "watching", "watched"], "c": 0},
    {"q": "Does she ___ a sister?", "o": ["has", "have", "having", "had"], "c": 1},
    {"q": "I ___ up early.", "o": ["get", "gets", "getting", "got"], "c": 0},
    {"q": "The baby ___ a lot.", "o": ["cry", "cries", "crying", "cried"], "c": 1},
    {"q": "Water ___ no taste.", "o": ["has", "have", "is having", "having"], "c": 0},

    # --- LEVEL: ELEMENTARY (Negative, Question, Adverbs of frequency) ---
    {"q": "I always ___ my homework.", "o": ["do", "does", "doing", "done"], "c": 0},
    {"q": "She never ___ coffee.", "o": ["drink", "drinks", "drinking", "drunk"], "c": 1},
    {"q": "We usually ___ to the park.", "o": ["go", "goes", "going", "went"], "c": 0},
    {"q": "They often ___ their grandparents.", "o": ["visit", "visits", "visiting", "visited"], "c": 0},
    {"q": "It seldom ___ in the desert.", "o": ["rain", "rains", "raining", "rained"], "c": 1},
    {"q": "Do you sometimes ___ late?", "o": ["work", "works", "working", "worked"], "c": 0},
    {"q": "He doesn't ___ much money.", "o": ["earns", "earn", "earning", "earned"], "c": 1},
    {"q": "My dog ___ when it sees a cat.", "o": ["bark", "barks", "barking", "barked"], "c": 1},
    {"q": "The lesson ___ at 9:00.", "o": ["start", "starts", "starting", "started"], "c": 1},
    {"q": "I don't ___ where she is.", "o": ["know", "knows", "knowing", "knew"], "c": 0},
    {"q": "Where ___ your father work?", "o": ["do", "does", "is", "are"], "c": 1},
    {"q": "How ___ you spell your name?", "o": ["do", "does", "are", "is"], "c": 0},
    {"q": "She ___ English very well.", "o": ["teaches", "teach", "teaching", "taught"], "c": 0},
    {"q": "We ___ at the same office.", "o": ["work", "works", "working", "worked"], "c": 0},
    {"q": "Fish ___ in the water.", "o": ["lives", "live", "living", "lived"], "c": 1},
    {"q": "My sister ___ to be a doctor.", "o": ["want", "wants", "wanting", "wanted"], "c": 1},
    {"q": "Does he ___ to the radio?", "o": ["listen", "listens", "listening", "listened"], "c": 0},
    {"q": "The shops ___ at 8 o'clock.", "o": ["opens", "open", "opening", "opened"], "c": 1},
    {"q": "I ___ fruit.", "o": ["loves", "love", "loving", "loved"], "c": 1},
    {"q": "The children ___ in the garden.", "o": ["play", "plays", "playing", "played"], "c": 0},
    {"q": "___ you like pizza?", "o": ["Does", "Is", "Do", "Are"], "c": 2},
    {"q": "She ___ her hair every morning.", "o": ["brush", "brushes", "brushing", "brushed"], "c": 1},
    {"q": "They ___ have a car.", "o": ["doesn't", "don't", "isn't", "haven't"], "c": 1},
    {"q": "A year ___ 12 months.", "o": ["has", "have", "having", "is having"], "c": 0},
    {"q": "What time ___ you go to bed?", "o": ["do", "does", "are", "is"], "c": 0},

    # --- LEVEL: INTERMEDIATE (Stative verbs, General Truths, Timetables) ---
    {"q": "The Earth ___ around the Sun.", "o": ["revolve", "revolves", "is revolving", "revolved"], "c": 1},
    {"q": "Water ___ at 100 degrees Celsius.", "o": ["boil", "is boiling", "boils", "boiled"], "c": 2},
    {"q": "The train ___ at 6:00 PM tonight.", "o": ["leave", "leaves", "is leaving", "will leave"], "c": 1},
    {"q": "I ___ what you mean.", "o": ["am understanding", "understand", "understands", "understood"], "c": 1},
    {"q": "This milk ___ sour.", "o": ["is tasting", "tastes", "taste", "tasted"], "c": 1},
    {"q": "Success ___ on your efforts.", "o": ["depend", "depends", "is depending", "depending"], "c": 1},
    {"q": "I ___ ghosts aren't real.", "o": ["believes", "believe", "am believing", "believing"], "c": 1},
    {"q": "She ___ like her mother.", "o": ["look", "looks", "is looking", "looked"], "c": 1},
    {"q": "The museum ___ at 10 AM daily.", "o": ["open", "opens", "is opening", "opened"], "c": 1},
    {"q": "Who ___ this book belong to?", "o": ["do", "does", "is", "are"], "c": 1},
    {"q": "I ___ much free time these days.", "o": ["haven't", "don't have", "doesn't have", "not have"], "c": 1},
    {"q": "The human brain ___ many neurons.", "o": ["contain", "contains", "is containing", "contained"], "c": 1},
    {"q": "I rarely ___ late for work.", "o": ["am", "is", "are", "be"], "c": 0},
    {"q": "Wood ___ on water.", "o": ["floats", "float", "floating", "floated"], "c": 0},
    {"q": "Why ___ he always complain?", "o": ["do", "does", "is", "are"], "c": 1},
    {"q": "It ___ a lot of energy to run a marathon.", "o": ["take", "takes", "taking", "taken"], "c": 1},
    {"q": "How much ___ this costs?", "o": ["is", "do", "does", "are"], "c": 2},
    {"q": "My glasses ___ on the table.", "o": ["is", "are", "am", "be"], "c": 1},
    {"q": "I ___ my keys. Have you seen them?", "o": ["lose", "forget", "always lose", "loses"], "c": 2},
    {"q": "The plane ___ in ten minutes.", "o": ["land", "lands", "is landing", "landed"], "c": 1},
    {"q": "She ___ a great memory.", "o": ["has", "have", "is having", "having"], "c": 0},
    {"q": "Practice ___ perfect.", "o": ["make", "makes", "making", "made"], "c": 1},
    {"q": "Money ___ on trees.", "o": ["doesn't grow", "don't grow", "isn't grow", "not grows"], "c": 0},
    {"q": "I ___ agree with you.", "o": ["am not", "don't", "doesn't", "no"], "c": 1},
    {"q": "The price of bread ___ every year.", "o": ["rise", "rises", "rising", "rose"], "c": 1},

    # --- LEVEL: MIXED (Various scenarios) ---
    {"q": "He ___ to the gym twice a week.", "o": ["go", "goes", "going", "gone"], "c": 1},
    {"q": "The stars ___ at night.", "o": ["shines", "shine", "shining", "shone"], "c": 1},
    {"q": "My watch ___ the correct time.", "o": ["show", "shows", "showing", "showed"], "c": 1},
    {"q": "We ___ any pets.", "o": ["doesn't have", "don't have", "haven't", "not have"], "c": 1},
    {"q": "What ___ you do for a living?", "o": ["do", "does", "are", "is"], "c": 0},
    {"q": "The ice ___ in the sun.", "o": ["melt", "melts", "melting", "melted"], "c": 1},
    {"q": "I ___ my parents every Sunday.", "o": ["call", "calls", "calling", "called"], "c": 0},
    {"q": "Does your boss ___ you?", "o": ["help", "helps", "helping", "helped"], "c": 0},
    {"q": "The coffee ___ great.", "o": ["smell", "smells", "smelling", "smelt"], "c": 1},
    {"q": "They ___ want to stay here.", "o": ["don't", "doesn't", "not", "aren't"], "c": 0},
    {"q": "My brother ___ more than me.", "o": ["read", "reads", "reading", "readed"], "c": 1},
    {"q": "Vegetables ___ vitamins.", "o": ["contains", "contain", "containing", "contained"], "c": 1},
    {"q": "I ___ my tea without sugar.", "o": ["takes", "take", "taking", "taken"], "c": 1},
    {"q": "The road ___ to the city.", "o": ["lead", "leads", "leading", "led"], "c": 1},
    {"q": "It ___ very cold in winter.", "o": ["is", "are", "am", "be"], "c": 0},
    {"q": "She ___ too much TV.", "o": ["watch", "watches", "watching", "watched"], "c": 1},
    {"q": "___ you need any help?", "o": ["Does", "Do", "Are", "Is"], "c": 1},
    {"q": "The company ___ 50 people.", "o": ["employ", "employs", "employing", "employed"], "c": 1},
    {"q": "I ___ bored in history class.", "o": ["feel", "feels", "feeling", "felt"], "c": 0},
    {"q": "He ___ the guitar beautifully.", "o": ["play", "plays", "playing", "played"], "c": 1},
    {"q": "Cats ___ in the dark.", "o": ["see", "sees", "seeing", "saw"], "c": 0},
    {"q": "Everything ___ on the weather.", "o": ["depends", "depend", "depending", "depended"], "c": 0},
    {"q": "We ___ tea in the morning.", "o": ["drink", "drinks", "drinking", "drank"], "c": 0},
    {"q": "The moon ___ around the Earth.", "o": ["go", "goes", "going", "went"], "c": 1},
    {"q": "I ___ hope you win.", "o": ["really", "do", "am", "is"], "c": 1},
# PRESENT_SIMPLE_QUIZ davomi (101 - 200)
    # --- Professional & Daily Life ---
    {"q": "A dentist ___ people's teeth.", "o": ["fix", "fixes", "is fixing", "fixed"], "c": 1},
    {"q": "The postman ___ the mail every morning.", "o": ["delivers", "deliver", "delivering", "delivered"], "c": 0},
    {"q": "My uncle ___ a taxi in New York.", "o": ["drive", "drives", "is driving", "driven"], "c": 1},
    {"q": "Architects ___ plans for new buildings.", "o": ["draws", "draw", "drawing", "drew"], "c": 1},
    {"q": "A chef ___ in a restaurant kitchen.", "o": ["cooks", "cook", "is cooking", "cooked"], "c": 0},
    {"q": "Mechanics ___ broken cars.", "o": ["repairs", "repair", "repairing", "repaired"], "c": 1},
    {"q": "I ___ my emails before starting work.", "o": ["check", "checks", "checking", "checked"], "c": 0},
    {"q": "She ___ yoga twice a week.", "o": ["do", "does", "doing", "did"], "c": 1},
    {"q": "We ___ lunch in the canteen at 1:00.", "o": ["has", "have", "is having", "having"], "c": 1},
    {"q": "It ___ a lot of time to learn a language.", "o": ["take", "takes", "taking", "taken"], "c": 1},
    {"q": "They ___ for a big bank.", "o": ["works", "work", "working", "worked"], "c": 1},
    {"q": "Does your father ___ the garden?", "o": ["mow", "mows", "mowing", "mowed"], "c": 0},
    {"q": "The secretary ___ phone calls all day.", "o": ["answer", "answers", "answering", "answered"], "c": 1},
    {"q": "I ___ remember to lock the door.", "o": ["always", "is", "am", "do"], "c": 0},
    {"q": "He ___ the trash out every night.", "o": ["take", "takes", "taking", "took"], "c": 1},
    {"q": "Farmers ___ crops in the fields.", "o": ["grow", "grows", "growing", "grown"], "c": 0},
    {"q": "My boss ___ very fast.", "o": ["speak", "speaks", "speaking", "spoke"], "c": 1},
    {"q": "We ___ any meetings on Mondays.", "o": ["not have", "doesn't have", "don't have", "haven't"], "c": 2},
    {"q": "The shop assistant ___ customers.", "o": ["help", "helps", "helping", "helped"], "c": 1},
    {"q": "How many hours ___ you sleep?", "o": ["do", "does", "are", "is"], "c": 0},

    # --- Habits & General Facts ---
    {"q": "Snakes ___ legs.", "o": ["don't have", "doesn't have", "not have", "haven't"], "c": 0},
    {"q": "The heart ___ blood through the body.", "o": ["pump", "pumps", "pumping", "pumped"], "c": 1},
    {"q": "Spiders ___ eight legs.", "o": ["has", "have", "is having", "having"], "c": 1},
    {"q": "An island ___ surrounded by water.", "o": ["is", "are", "am", "be"], "c": 0},
    {"q": "The stars ___ during the day.", "o": ["not shine", "doesn't shine", "don't shine", "isn't shining"], "c": 2},
    {"q": "I ___ my bed every morning.", "o": ["make", "makes", "making", "made"], "c": 0},
    {"q": "She ___ her nails once a week.", "o": ["cut", "cuts", "cutting", "cutted"], "c": 1},
    {"q": "My neighbors ___ a loud dog.", "o": ["has", "have", "having", "is having"], "c": 1},
    {"q": "Honey ___ from bees.", "o": ["come", "comes", "coming", "came"], "c": 1},
    {"q": "Children ___ fast when they are young.", "o": ["grow", "grows", "growing", "grown"], "c": 0},
    {"q": "I ___ read the newspaper online.", "o": ["usually", "is", "do", "am"], "c": 0},
    {"q": "The bank ___ at 5:00 PM.", "o": ["close", "is closing", "closes", "closed"], "c": 2},
    {"q": "We ___ vegetables in our garden.", "o": ["plant", "plants", "planting", "planted"], "c": 0},
    {"q": "It ___ very hot in summer here.", "o": ["is", "are", "get", "gets"], "c": 0},
    {"q": "Do cats ___ water?", "o": ["hates", "hate", "hating", "hated"], "c": 1},
    {"q": "The internet ___ a lot of information.", "o": ["contain", "contains", "is containing", "contained"], "c": 1},
    {"q": "He ___ late for dinner every day.", "o": ["comes", "come", "coming", "came"], "c": 0},
    {"q": "I ___ my keys on the table.", "o": ["leaves", "leave", "left", "leaving"], "c": 1},
    {"q": "Does it ___ often in winter?", "o": ["snows", "snow", "snowing", "snowed"], "c": 1},
    {"q": "They ___ to the radio in the car.", "o": ["listens", "listen", "listening", "listened"], "c": 1},

    # --- Intermediate Focus (Stative verbs & Logic) ---
    {"q": "I ___ that you are tired.", "o": ["am thinking", "think", "thinks", "thought"], "c": 1},
    {"q": "This perfume ___ like roses.", "o": ["smell", "smells", "is smelling", "smelled"], "c": 1},
    {"q": "Do you ___ how much it costs?", "o": ["knowing", "know", "knows", "knew"], "c": 1},
    {"q": "She ___ to be very happy.", "o": ["seems", "seem", "is seeming", "seemed"], "c": 0},
    {"q": "I ___ my old school friends.", "o": ["misses", "miss", "missing", "am missing"], "c": 1},
    {"q": "This bag ___ to my brother.", "o": ["belong", "belongs", "is belonging", "belonged"], "c": 1},
    {"q": "I ___ with you on this point.", "o": ["agree", "agrees", "am agreeing", "agreed"], "c": 0},
    {"q": "Does this box ___ everything?", "o": ["contain", "contains", "containing", "contained"], "c": 0},
    {"q": "I ___ what you are saying.", "o": ["understands", "understand", "am understanding", "understood"], "c": 1},
    {"q": "He ___ to need some help.", "o": ["appear", "appears", "appearing", "appeared"], "c": 1},
    {"q": "They ___ a lot of money.", "o": ["owe", "owes", "owing", "owed"], "c": 0},
    {"q": "I ___ my coffee black.", "o": ["prefers", "prefer", "preferring", "preferred"], "c": 1},
    {"q": "The cake ___ delicious.", "o": ["taste", "is tasting", "tastes", "tasted"], "c": 2},
    {"q": "___ you recognize that man?", "o": ["Do", "Are", "Does", "Is"], "c": 0},
    {"q": "It ___ matter if you are late.", "o": ["doesn't", "don't", "isn't", "not"], "c": 0},
    {"q": "We ___ a better solution.", "o": ["need", "needs", "needing", "needed"], "c": 0},
    {"q": "I ___ her name now.", "o": ["remembers", "remembering", "remember", "remembered"], "c": 2},
    {"q": "This dress ___ you perfectly.", "o": ["fit", "fits", "fitting", "is fitting"], "c": 1},
    {"q": "I ___ believe his story.", "o": ["don't", "doesn't", "not", "am not"], "c": 0},
    {"q": "How much ___ that car weigh?", "o": ["do", "is", "does", "are"], "c": 2},

    # --- Beginner Re-focus (Negative & Basic Questions) ---
    {"q": "She ___ play tennis.", "o": ["don't", "not", "doesn't", "isn't"], "c": 2},
    {"q": "We ___ drink milk.", "o": ["not", "don't", "doesn't", "aren't"], "c": 1},
    {"q": "They ___ students.", "o": ["am not", "isn't", "aren't", "don't"], "c": 2},
    {"q": "___ you like ice cream?", "o": ["Do", "Does", "Are", "Is"], "c": 0},
    {"q": "Where ___ she live?", "o": ["do", "does", "is", "are"], "c": 1},
    {"q": "I ___ not a doctor.", "o": ["am", "is", "are", "be"], "c": 0},
    {"q": "My dog ___ cats.", "o": ["hate", "hates", "hating", "hated"], "c": 1},
    {"q": "It ___ a small room.", "o": ["am", "is", "are", "be"], "c": 1},
    {"q": "You ___ speak very loud.", "o": ["not", "doesn't", "don't", "aren't"], "c": 2},
    {"q": "___ it cold today?", "o": ["Is", "Are", "Am", "Do"], "c": 0},
    {"q": "We ___ at 6 AM.", "o": ["wake up", "wakes up", "waking up", "woke up"], "c": 0},
    {"q": "He ___ tea, not coffee.", "o": ["drink", "drinks", "drinking", "drunk"], "c": 1},
    {"q": "The birds ___ every morning.", "o": ["sing", "sings", "singing", "sang"], "c": 0},
    {"q": "___ you have any brothers?", "o": ["Do", "Does", "Are", "Is"], "c": 0},
    {"q": "She ___ home by bus.", "o": ["come", "comes", "coming", "came"], "c": 1},
    {"q": "I ___ go to the park on Sundays.", "o": ["always", "is", "am", "be"], "c": 0},
    {"q": "My mom ___ English.", "o": ["teach", "teaches", "teaching", "taught"], "c": 1},
    {"q": "The sun ___ in the evening.", "o": ["sets", "set", "setting", "setted"], "c": 0},
    {"q": "Do they ___ play football?", "o": ["often", "is", "are", "am"], "c": 0},
    {"q": "I ___ my hands before eating.", "o": ["wash", "washes", "washing", "washed"], "c": 0},

    # --- Everyday Objects & Facts ---
    {"q": "Cameras ___ pictures.", "o": ["takes", "take", "taking", "taken"], "c": 1},
    {"q": "A clock ___ the time.", "o": ["tells", "tell", "telling", "told"], "c": 0},
    {"q": "Buses ___ at this stop.", "o": ["stop", "stops", "stopping", "stopped"], "c": 0},
    {"q": "A baker ___ bread.", "o": ["sell", "sells", "selling", "sold"], "c": 1},
    {"q": "Rain ___ from the clouds.", "o": ["fall", "falls", "falling", "fell"], "c": 1},
    {"q": "Does fire ___ heat?", "o": ["produce", "produces", "producing", "produced"], "c": 0},
    {"q": "Wood ___ in the fireplace.", "o": ["burn", "burns", "burning", "burnt"], "c": 1},
    {"q": "I ___ with my eyes.", "o": ["see", "sees", "seeing", "saw"], "c": 0},
    {"q": "Ears ___ us to hear.", "o": ["help", "helps", "helping", "helped"], "c": 0},
    {"q": "Sugar ___ sweet.", "o": ["is", "are", "am", "be"], "c": 0},
    {"q": "Lemons ___ sour.", "o": ["is", "are", "am", "be"], "c": 1},
    {"q": "Winter ___ after Autumn.", "o": ["come", "comes", "coming", "came"], "c": 1},
    {"q": "Leaves ___ in the Autumn.", "o": ["fall", "falls", "falling", "fell"], "c": 0},
    {"q": "I ___ my teeth after breakfast.", "o": ["brush", "brushes", "brushing", "brushed"], "c": 0},
    {"q": "He ___ for the bus every morning.", "o": ["wait", "waits", "waiting", "waited"], "c": 1},
    {"q": "Do you ___ a lot of water?", "o": ["drink", "drinks", "drinking", "drank"], "c": 0},
    {"q": "She ___ a lot of books.", "o": ["buy", "buys", "buying", "bought"], "c": 1},
    {"q": "We ___ our bicycles to the park.", "o": ["ride", "rides", "riding", "rode"], "c": 0},
    {"q": "The teacher ___ on the board.", "o": ["write", "writes", "writing", "wrote"], "c": 1},
    {"q": "I ___ a pen to write.", "o": ["use", "uses", "using", "used"], "c": 0},
# PRESENT_SIMPLE_QUIZ davomi (201 - 300)
    # --- Objects & Functionality ---
    {"q": "A thermometer ___ the temperature.", "o": ["measure", "measures", "measuring", "measured"], "c": 1},
    {"q": "The sun ___ us with light and heat.", "o": ["provides", "provide", "providing", "provided"], "c": 0},
    {"q": "These machines ___ a lot of noise.", "o": ["makes", "make", "making", "made"], "c": 1},
    {"q": "Does your phone ___ a good camera?", "o": ["has", "have", "having", "had"], "c": 1},
    {"q": "Electric cars ___ petrol.", "o": ["doesn't need", "don't need", "not need", "aren't needing"], "c": 1},
    {"q": "The fridge ___ the food cold.", "o": ["keeps", "keep", "keeping", "kept"], "c": 0},
    {"q": "Brakes ___ a car to stop.", "o": ["help", "helps", "helping", "helped"], "c": 0},
    {"q": "This key ___ the front door.", "o": ["open", "opens", "opening", "opened"], "c": 1},
    {"q": "Erasers ___ pencil marks.", "o": ["removes", "remove", "removing", "removed"], "c": 1},
    {"q": "The alarm clock ___ at 7:00.", "o": ["ring", "rings", "ringing", "rang"], "c": 1},

    # --- Animals & Nature ---
    {"q": "Lions ___ in groups called prides.", "o": ["lives", "live", "living", "lived"], "c": 1},
    {"q": "A polar bear ___ white fur.", "o": ["have", "has", "is having", "having"], "c": 1},
    {"q": "Bees ___ honey from nectar.", "o": ["produces", "produce", "producing", "produced"], "c": 1},
    {"q": "The moon ___ its own light.", "o": ["doesn't have", "don't have", "isn't having", "not has"], "c": 0},
    {"q": "Plants ___ carbon dioxide.", "o": ["absorbs", "absorb", "absorbing", "absorbed"], "c": 1},
    {"q": "Rivers ___ towards the ocean.", "o": ["flow", "flows", "flowing", "flowed"], "c": 0},
    {"q": "Does it ___ often in London?", "o": ["rain", "rains", "raining", "rained"], "c": 0},
    {"q": "Camels ___ a lot of water at once.", "o": ["drink", "drinks", "drinking", "drank"], "c": 0},
    {"q": "Trees ___ their leaves in winter.", "o": ["loses", "lose", "losing", "lost"], "c": 1},
    {"q": "Gravity ___ objects to the ground.", "o": ["pull", "pulls", "pulling", "pulled"], "c": 1},

    # --- Daily Habits & Routines ---
    {"q": "I usually ___ my clothes in the evening.", "o": ["iron", "irons", "ironing", "ironed"], "c": 0},
    {"q": "She ___ her bed every single day.", "o": ["make", "makes", "making", "made"], "c": 1},
    {"q": "We ___ any coffee in the house.", "o": ["not have", "doesn't have", "don't have", "haven't"], "c": 2},
    {"q": "He ___ to the gym before work.", "o": ["go", "goes", "going", "gone"], "c": 1},
    {"q": "I ___ my emails every hour.", "o": ["checks", "check", "checking", "checked"], "c": 1},
    {"q": "They ___ dinner together as a family.", "o": ["eat", "eats", "eating", "ate"], "c": 0},
    {"q": "Do you ___ your car every weekend?", "o": ["washes", "wash", "washing", "washed"], "c": 1},
    {"q": "My sister ___ at a local hospital.", "o": ["work", "works", "working", "worked"], "c": 1},
    {"q": "I ___ my hair twice a month.", "o": ["cut", "cuts", "cutting", "am cutting"], "c": 0},
    {"q": "We ___ usually stay up late.", "o": ["don't", "doesn't", "aren't", "not"], "c": 0},

    # --- Emotions & Mental States (Stative Verbs) ---
    {"q": "I ___ your help very much.", "o": ["appreciate", "appreciates", "am appreciating", "appreciated"], "c": 0},
    {"q": "She ___ that she is wrong.", "o": ["know", "knows", "is knowing", "known"], "c": 1},
    {"q": "They ___ to be tired after the trip.", "o": ["seem", "seems", "seeming", "seemed"], "c": 0},
    {"q": "I ___ what you are going through.", "o": ["understands", "understand", "am understanding", "understood"], "c": 1},
    {"q": "Does he ___ the truth?", "o": ["knows", "know", "knowing", "knew"], "c": 1},
    {"q": "I ___ my best friend very much.", "o": ["trusts", "trust", "am trusting", "trusted"], "c": 1},
    {"q": "She ___ her parents' advice.", "o": ["value", "values", "valuing", "valued"], "c": 1},
    {"q": "We ___ some more time to decide.", "o": ["needs", "need", "needing", "needed"], "c": 1},
    {"q": "I ___ in world peace.", "o": ["believes", "believe", "am believing", "believing"], "c": 1},
    {"q": "He ___ to like his new job.", "o": ["appears", "appear", "appearing", "appeared"], "c": 0},

    # --- Timetables & Schedules ---
    {"q": "The library ___ at 8:00 AM.", "o": ["open", "opens", "is opening", "opened"], "c": 1},
    {"q": "What time ___ the next bus arrive?", "o": ["do", "is", "does", "are"], "c": 2},
    {"q": "The semester ___ in September.", "o": ["start", "starts", "starting", "started"], "c": 1},
    {"q": "My flight ___ off at 10:30.", "o": ["take", "takes", "taking", "took"], "c": 1},
    {"q": "The movie ___ at 9:00 PM tonight.", "o": ["end", "ends", "ending", "ended"], "c": 1},
    {"q": "We ___ a meeting tomorrow morning.", "o": ["has", "have", "is having", "having"], "c": 1},
    {"q": "The match ___ in a draw.", "o": ["finish", "finishes", "finishing", "finished"], "c": 1},
    {"q": "When ___ the bank close?", "o": ["do", "does", "is", "are"], "c": 1},
    {"q": "The concert ___ for two hours.", "o": ["last", "lasts", "lasting", "lasted"], "c": 1},
    {"q": "Registration ___ next Friday.", "o": ["closes", "close", "is closing", "closed"], "c": 0},

    # --- Beginner Level Focus ---
    {"q": "I ___ not a teacher.", "o": ["am", "is", "are", "be"], "c": 0},
    {"q": "She ___ from France.", "o": ["is", "are", "am", "be"], "c": 0},
    {"q": "They ___ my cousins.", "o": ["is", "are", "am", "be"], "c": 1},
    {"q": "It ___ very hot today.", "o": ["is", "are", "am", "be"], "c": 0},
    {"q": "___ you a doctor?", "o": ["Are", "Is", "Am", "Do"], "c": 0},
    {"q": "We ___ at home right now.", "o": ["is", "are", "am", "be"], "c": 1},
    {"q": "___ he your classmate?", "o": ["Are", "Is", "Am", "Do"], "c": 1},
    {"q": "I ___ a new bike.", "o": ["has", "have", "is having", "having"], "c": 1},
    {"q": "She ___ blue eyes.", "o": ["has", "have", "is having", "having"], "c": 0},
    {"q": "It ___ a beautiful flower.", "o": ["is", "are", "am", "be"], "c": 0},

    # --- Question & Negative Practice ---
    {"q": "___ you speak Spanish?", "o": ["Does", "Is", "Do", "Are"], "c": 2},
    {"q": "She ___ like spicy food.", "o": ["don't", "doesn't", "not", "isn't"], "c": 1},
    {"q": "We ___ live in a flat.", "o": ["don't", "doesn't", "aren't", "not"], "c": 0},
    {"q": "___ they work on Sundays?", "o": ["Does", "Do", "Are", "Is"], "c": 1},
    {"q": "He ___ study at night.", "o": ["don't", "doesn't", "not", "isn't"], "c": 1},
    {"q": "Where ___ you go on vacation?", "o": ["do", "does", "is", "are"], "c": 0},
    {"q": "What ___ she do for fun?", "o": ["do", "does", "is", "are"], "c": 1},
    {"q": "How ___ you go to work?", "o": ["do", "does", "is", "are"], "c": 0},
    {"q": "Why ___ they always late?", "o": ["is", "are", "do", "does"], "c": 1},
    {"q": "___ it cost a lot of money?", "o": ["Do", "Is", "Does", "Has"], "c": 2},

    # --- General Verbs ---
    {"q": "I ___ my face every morning.", "o": ["wash", "washes", "washing", "washed"], "c": 0},
    {"q": "She ___ the newspaper every day.", "o": ["read", "reads", "reading", "readed"], "c": 1},
    {"q": "They ___ to school by bus.", "o": ["go", "goes", "going", "gone"], "c": 0},
    {"q": "We ___ our lunch at 12:00.", "o": ["eat", "eats", "eating", "ate"], "c": 0},
    {"q": "He ___ the guitar very well.", "o": ["play", "plays", "playing", "played"], "c": 1},
    {"q": "The cat ___ on the mat.", "o": ["sit", "sits", "sitting", "sat"], "c": 1},
    {"q": "I ___ my teeth after dinner.", "o": ["brush", "brushes", "brushing", "brushed"], "c": 0},
    {"q": "The birds ___ in the garden.", "o": ["sing", "sings", "singing", "sang"], "c": 1},
    {"q": "It ___ a lot in autumn.", "o": ["rain", "rains", "raining", "rained"], "c": 1},
    {"q": "She ___ a cup of tea.", "o": ["want", "wants", "wanting", "wanted"], "c": 1},

    # --- Mix & Match ---
    {"q": "Knowledge ___ power.", "o": ["is", "are", "be", "am"], "c": 0},
    {"q": "Honest people ___ the truth.", "o": ["tells", "tell", "telling", "told"], "c": 1},
    {"q": "Does she ___ anyone here?", "o": ["know", "knows", "knowing", "knew"], "c": 0},
    {"q": "I ___ my room once a week.", "o": ["clean", "cleans", "cleaning", "cleaned"], "c": 0},
    {"q": "He ___ very fast.", "o": ["run", "runs", "running", "ran"], "c": 1},
    {"q": "They ___ English lessons.", "o": ["has", "have", "is having", "having"], "c": 1},
    {"q": "My dog ___ at strangers.", "o": ["bark", "barks", "barking", "barked"], "c": 1},
    {"q": "Water ___ no color.", "o": ["has", "have", "is having", "having"], "c": 0},
    {"q": "___ you hungry?", "o": ["Is", "Are", "Am", "Do"], "c": 1},
    {"q": "He ___ not like chocolate.", "o": ["do", "does", "is", "not"], "c": 1},
    {"q": "The sky ___ blue.", "o": ["is", "are", "am", "be"], "c": 0},
    {"q": "I ___ with a pen.", "o": ["write", "writes", "writing", "wrote"], "c": 0},
    {"q": "She ___ too much.", "o": ["talk", "talks", "talking", "talked"], "c": 1},
    {"q": "We ___ our country.", "o": ["love", "loves", "loving", "loved"], "c": 0},
    {"q": "It ___ cold in the fridge.", "o": ["is", "are", "am", "be"], "c": 0},
    {"q": "Do you ___ any pets?", "o": ["has", "have", "having", "had"], "c": 1},
    {"q": "He ___ a big car.", "o": ["drive", "drives", "driving", "drove"], "c": 1},
    {"q": "They ___ at the park.", "o": ["is", "are", "am", "be"], "c": 1},
    {"q": "I ___ tired.", "o": ["am", "is", "are", "be"], "c": 0},
    {"q": "She ___ very smart.", "o": ["is", "are", "am", "be"], "c": 0}
]




