PRESENT_CONTINUOUS_QUIZ = [
    # --- LEVEL: BEGINNER (Am/Is/Are + V-ing) ---
    {"q": "Look! The baby ___.", "o": ["is sleeping", "sleeps", "are sleeping", "sleep"], "c": 0},
    {"q": "I ___ my homework right now.", "o": ["am doing", "is doing", "do", "doing"], "c": 0},
    {"q": "Listen! Someone ___ the piano.", "o": ["plays", "play", "is playing", "are playing"], "c": 2},
    {"q": "They ___ football in the garden at the moment.", "o": ["is playing", "are playing", "play", "plays"], "c": 1},
    {"q": "She ___ a blue dress today.", "o": ["wears", "is wearing", "wear", "are wearing"], "c": 1},
    {"q": "We ___ for the bus right now.", "o": ["is waiting", "wait", "are waiting", "waiting"], "c": 2},
    {"q": "It ___ outside at the moment.", "o": ["is raining", "rains", "are raining", "rain"], "c": 0},
    {"q": "You ___ very fast. Please slow down!", "o": ["walk", "is walking", "are walking", "walks"], "c": 2},
    {"q": "My mom ___ dinner in the kitchen now.", "o": ["is cooking", "cooks", "cook", "are cooking"], "c": 0},
    {"q": "I ___ to music at this moment.", "o": ["listen", "am listening", "is listening", "listening"], "c": 1},
    {"q": "Look! The cat ___ the tree.", "o": ["climb", "is climbing", "climbs", "are climbing"], "c": 1},
    {"q": "We ___ English lessons this week.", "o": ["have", "is having", "are having", "has"], "c": 2},
    {"q": "The students ___ for their exams now.", "o": ["study", "is studying", "are studying", "studies"], "c": 2},
    {"q": "___ you watching TV right now?", "o": ["Are", "Is", "Do", "Am"], "c": 0},
    {"q": "He ___ not working today. He is ill.", "o": ["am", "is", "are", "be"], "c": 1},
    {"q": "Where ___ she going?", "o": ["is", "are", "am", "do"], "c": 0},
    {"q": "They ___ a new house this month.", "o": ["build", "is building", "are building", "builds"], "c": 2},
    {"q": "Shh! I ___ on the phone.", "o": ["am talking", "talk", "is talking", "talking"], "c": 0},
    {"q": "The birds ___ south for the winter.", "o": ["fly", "is flying", "are flying", "flies"], "c": 2},
    {"q": "What ___ you doing under the table?", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "My father ___ the car in the garage.", "o": ["wash", "is washing", "washes", "are washing"], "c": 1},
    {"q": "We ___ a party tonight. Come over!", "o": ["have", "is having", "are having", "has"], "c": 2},
    {"q": "Look! It ___ to snow.", "o": ["start", "is starting", "starts", "starting"], "c": 1},
    {"q": "The sun ___ brightly today.", "o": ["is shining", "shines", "shine", "are shining"], "c": 0},
    {"q": "I ___ my room at the moment.", "o": ["clean", "am cleaning", "is cleaning", "cleans"], "c": 1},

    # --- LEVEL: ELEMENTARY (Spelling & Questions) ---
    {"q": "Wait! I ___ to help you.", "o": ["coming", "am coming", "is coming", "come"], "c": 1},
    {"q": "Why ___ they running so fast?", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "The teacher ___ on the whiteboard now.", "o": ["write", "is writing", "writes", "writing"], "c": 1},
    {"q": "I ___ not feeling well today.", "o": ["am", "is", "are", "be"], "c": 0},
    {"q": "Who ___ you talking to?", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "My friends ___ a movie at my house.", "o": ["is watching", "are watching", "watch", "watches"], "c": 1},
    {"q": "Look! The dog ___ after the ball.", "o": ["is running", "run", "runs", "are running"], "c": 0},
    {"q": "___ it getting dark outside?", "o": ["Is", "Are", "Am", "Does"], "c": 0},
    {"q": "We ___ our bags for the trip.", "o": ["pack", "is packing", "are packing", "packs"], "c": 2},
    {"q": "She ___ tea. She's drinking coffee.", "o": ["isn't drinking", "doesn't drink", "not drinking", "aren't drinking"], "c": 0},
    {"q": "I ___ my keys. I can't find them!", "o": ["am looking for", "look for", "is looking for", "looking"], "c": 0},
    {"q": "They ___ for the competition these days.", "o": ["train", "is training", "are training", "trains"], "c": 2},
    {"q": "What ___ your brother studying?", "o": ["is", "are", "am", "do"], "c": 0},
    {"q": "I ___ breakfast at the moment.", "o": ["am having", "have", "is having", "having"], "c": 0},
    {"q": "The water ___! Turn off the stove.", "o": ["boils", "is boiling", "boil", "are boiling"], "c": 1},
    {"q": "We ___ about you. Don't worry.", "o": ["are thinking", "think", "is thinking", "thinks"], "c": 0},
    {"q": "Look! The plane ___.", "o": ["land", "is landing", "lands", "are landing"], "c": 1},
    {"q": "The children ___ in the pool.", "o": ["swim", "is swimming", "are swimming", "swims"], "c": 2},
    {"q": "___ you listening to me?", "o": ["Are", "Is", "Am", "Do"], "c": 0},
    {"q": "He ___ for a new job this month.", "o": ["search", "is searching", "searches", "are searching"], "c": 1},
    {"q": "I ___ the guitar in my room.", "o": ["am playing", "play", "is playing", "playing"], "c": 0},
    {"q": "Why ___ she crying?", "o": ["is", "are", "am", "do"], "c": 0},
    {"q": "They ___ a lot of noise next door.", "o": ["make", "is making", "are making", "makes"], "c": 2},
    {"q": "My sister ___ for her wedding.", "o": ["prepare", "is preparing", "prepares", "preparing"], "c": 1},
    {"q": "We ___ dinner out tonight.", "o": ["is eating", "are eating", "eat", "eats"], "c": 1},

    # --- LEVEL: INTERMEDIATE (Future arrangements & Special verbs) ---
    {"q": "I ___ my dentist tomorrow at 10 AM.", "o": ["am seeing", "see", "sees", "am seen"], "c": 0},
    {"q": "What time ___ they arriving tonight?", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "We ___ to London next Friday.", "o": ["fly", "is flying", "are flying", "flies"], "c": 2},
    {"q": "She ___ a presentation at 2 PM.", "o": ["give", "is giving", "gives", "giving"], "c": 1},
    {"q": "I ___ lunch with Sarah this afternoon.", "o": ["am having", "have", "is having", "has"], "c": 0},
    {"q": "___ you doing anything this weekend?", "o": ["Are", "Is", "Am", "Do"], "c": 0},
    {"q": "My parents ___ over for dinner on Sunday.", "o": ["come", "is coming", "are coming", "comes"], "c": 2},
    {"q": "He ___ his new car tomorrow.", "o": ["pick up", "is picking up", "picks up", "picking"], "c": 1},
    {"q": "I ___ on a business trip next week.", "o": ["go", "is going", "am going", "goes"], "c": 2},
    {"q": "They ___ married in June.", "o": ["get", "is getting", "are getting", "gets"], "c": 2},
    {"q": "The population of the world ___ very fast.", "o": ["increase", "is increasing", "increases", "are increasing"], "c": 1},
    {"q": "Your English ___ better and better.", "o": ["get", "is getting", "gets", "are getting"], "c": 1},
    {"q": "The weather ___ colder these days.", "o": ["become", "is becoming", "becomes", "are becoming"], "c": 1},
    {"q": "I ___ more tired as the day goes on.", "o": ["get", "am getting", "is getting", "gets"], "c": 1},
    {"q": "The city ___ because of the new project.", "o": ["change", "is changing", "changes", "are changing"], "c": 1},
    {"q": "You ___ always losing your keys!", "o": ["are", "is", "am", "be"], "c": 0},
    {"q": "He ___ always complaining about his boss.", "o": ["is", "are", "am", "be"], "c": 0},
    {"q": "Why ___ you always interrupting me?", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "They ___ always making excuses.", "o": ["is", "are", "am", "be"], "c": 1},
    {"q": "It ___ always raining in this town.", "o": ["is", "are", "am", "be"], "c": 0},
    {"q": "I ___ currently staying at a hotel.", "o": ["am", "is", "are", "be"], "c": 0},
    {"q": "The company ___ for a new manager.", "o": ["look", "is looking", "looks", "are looking"], "c": 1},
    {"q": "We ___ a lot of progress this year.", "o": ["make", "is making", "are making", "makes"], "c": 2},
    {"q": "Prices ___ up again this month.", "o": ["go", "is going", "are going", "goes"], "c": 2},
    {"q": "She ___ hard to finish the project.", "o": ["work", "is working", "works", "working"], "c": 1},

    # --- LEVEL: MIXED (Various scenarios) ---
    {"q": "Look! That man ___ to open your car.", "o": ["try", "is trying", "tries", "are trying"], "c": 1},
    {"q": "I ___ to get a seat on this train.", "o": ["am trying", "try", "is trying", "trying"], "c": 0},
    {"q": "___ you waiting for someone?", "o": ["Are", "Is", "Am", "Do"], "c": 0},
    {"q": "They ___ a lot of photos right now.", "o": ["take", "is taking", "are taking", "takes"], "c": 2},
    {"q": "My brother ___ at the gym today.", "o": ["train", "is training", "trains", "are training"], "c": 1},
    {"q": "We ___ our holiday in Italy this year.", "o": ["spend", "is spending", "are spending", "spends"], "c": 2},
    {"q": "I ___ a book about history now.", "o": ["read", "am reading", "is reading", "reads"], "c": 1},
    {"q": "Look! The sun ___ up.", "o": ["come", "is coming", "comes", "are coming"], "c": 1},
    {"q": "He ___ for the marathon these days.", "o": ["is training", "trains", "train", "are training"], "c": 0},
    {"q": "Why ___ you wearing a coat? It's hot!", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "The bus ___ at the stop now.", "o": ["stop", "is stopping", "stops", "are stopping"], "c": 1},
    {"q": "We ___ our house this summer.", "o": ["paint", "is painting", "are painting", "paints"], "c": 2},
    {"q": "She ___ her car right now.", "o": ["drive", "is driving", "drives", "are driving"], "c": 1},
    {"q": "I ___ my coffee. It's too hot.", "o": ["am not drinking", "doesn't drink", "not drink", "don't drink"], "c": 0},
    {"q": "What ___ they laughing at?", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "Someone ___ at the door. Can you open it?", "o": ["knock", "is knocking", "knocks", "are knocking"], "c": 1},
    {"q": "We ___ a lot of fun at the beach!", "o": ["have", "is having", "are having", "has"], "c": 2},
    {"q": "Look! The stars ___ tonight.", "o": ["shine", "is shining", "are shining", "shines"], "c": 2},
    {"q": "I ___ a letter to my pen pal.", "o": ["am writing", "write", "is writing", "writing"], "c": 0},
    {"q": "___ he still working in the office?", "o": ["Is", "Are", "Am", "Does"], "c": 0},
    {"q": "The baby ___ because he is hungry.", "o": ["cry", "is crying", "cries", "are crying"], "c": 1},
    {"q": "We ___ the game at the moment.", "o": ["win", "is winning", "are winning", "wins"], "c": 2},
    {"q": "She ___ her lunch in the park.", "o": ["eat", "is eating", "eats", "are eating"], "c": 1},
    {"q": "I ___ my teeth. I'll be there in a minute.", "o": ["am brushing", "brush", "is brushing", "brushes"], "c": 0},
    {"q": "They ___ for the taxi outside.", "o": ["wait", "is waiting", "are waiting", "waits"], "c": 2},
# PRESENT_CONTINUOUS_QUIZ davomi (101 - 200)
    # --- Spelling & Action Verbs ---
    {"q": "The athletes ___ for the gold medal.", "o": ["is running", "are running", "run", "running"], "c": 1},
    {"q": "I ___ on the sofa right now.", "o": ["am sitting", "is sitting", "sit", "sitting"], "c": 0},
    {"q": "Look! The cat ___ on the floor.", "o": ["is lying", "is lieing", "lies", "are lying"], "c": 0},
    {"q": "They ___ a big hole in the garden.", "o": ["dig", "is digging", "are digging", "digs"], "c": 2},
    {"q": "She ___ a letter to her grandmother.", "o": ["is writing", "writes", "writing", "are writing"], "c": 0},
    {"q": "The swimmer ___ across the lake.", "o": ["is swimming", "swims", "swim", "are swimming"], "c": 0},
    {"q": "We ___ our lunch at the moment.", "o": ["is having", "have", "are having", "has"], "c": 2},
    {"q": "I ___ to fix my computer.", "o": ["am trying", "try", "is trying", "trying"], "c": 0},
    {"q": "Stop! You ___ too much noise.", "o": ["is making", "are making", "make", "makes"], "c": 1},
    {"q": "Look at them! They ___ a lot of fun.", "o": ["have", "is having", "are having", "has"], "c": 2},

    # --- Questions & Negatives ---
    {"q": "___ it raining outside?", "o": ["Are", "Is", "Does", "Am"], "c": 1},
    {"q": "Why ___ you wearing my shoes?", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "He ___ not listening to the teacher.", "o": ["is", "are", "am", "be"], "c": 0},
    {"q": "Where ___ they going for their vacation?", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "___ she studying for her test?", "o": ["Is", "Are", "Am", "Does"], "c": 0},
    {"q": "I ___ not watching the news right now.", "o": ["am", "is", "are", "be"], "c": 0},
    {"q": "What ___ you cooking? It smells good!", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "They ___ not working this weekend.", "o": ["is", "are", "am", "be"], "c": 1},
    {"q": "Who ___ she waiting for?", "o": ["is", "are", "am", "do"], "c": 0},
    {"q": "___ the children playing in the park?", "o": ["Is", "Are", "Am", "Do"], "c": 1},

    # --- Temporary Situations ---
    {"q": "My brother ___ at a local shop this summer.", "o": ["work", "is working", "works", "are working"], "c": 1},
    {"q": "I ___ with my aunt until I find a flat.", "o": ["stay", "am staying", "stays", "is staying"], "c": 1},
    {"q": "We ___ a lot of tests this week.", "o": ["have", "is having", "are having", "has"], "c": 2},
    {"q": "She ___ a course on photography this month.", "o": ["take", "is taking", "takes", "taking"], "c": 1},
    {"q": "They ___ to finish the project by Friday.", "o": ["try", "is trying", "are trying", "tries"], "c": 2},
    {"q": "The weather ___ warmer these days.", "o": ["get", "is getting", "gets", "are getting"], "c": 1},
    {"q": "I ___ more and more English every day.", "o": ["learn", "am learning", "is learning", "learning"], "c": 1},
    {"q": "Prices ___ up so fast lately.", "o": ["go", "is going", "are going", "goes"], "c": 2},
    {"q": "My English ___ slowly.", "o": ["improve", "is improving", "improves", "are improving"], "c": 1},
    {"q": "The city ___ because of the new mall.", "o": ["change", "is changing", "changes", "are changing"], "c": 1},

    # --- Fixed Arrangements (Future) ---
    {"q": "I ___ to the cinema tonight.", "o": ["go", "is going", "am going", "goes"], "c": 2},
    {"q": "We ___ tennis on Saturday morning.", "o": ["play", "is playing", "are playing", "plays"], "c": 2},
    {"q": "What ___ you doing tonight?", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "She ___ a doctor tomorrow at 3 PM.", "o": ["see", "is seeing", "sees", "seeing"], "c": 1},
    {"q": "My parents ___ for dinner this evening.", "o": ["come", "is coming", "are coming", "comes"], "c": 2},
    {"q": "They ___ to Paris next week.", "o": ["travel", "is traveling", "are traveling", "travels"], "c": 2},
    {"q": "I ___ my new job on Monday.", "o": ["start", "am starting", "is starting", "starts"], "c": 1},
    {"q": "We ___ a meeting with the boss at 10:00.", "o": ["have", "is having", "are having", "has"], "c": 2},
    {"q": "He ___ home early today.", "o": ["come", "is coming", "comes", "coming"], "c": 1},
    {"q": "___ you coming to the party tonight?", "o": ["Are", "Is", "Am", "Do"], "c": 0},

    # --- Annoying Habits (Always) ---
    {"q": "You ___ always interrupting me!", "o": ["is", "are", "am", "be"], "c": 1},
    {"q": "He ___ always losing his phone.", "o": ["is", "are", "am", "be"], "c": 0},
    {"q": "They ___ always making excuses.", "o": ["is", "are", "am", "be"], "c": 1},
    {"q": "She ___ always complaining about the weather.", "o": ["is", "are", "am", "be"], "c": 0},
    {"q": "I ___ always forgetting my keys.", "o": ["am", "is", "are", "be"], "c": 0},

    # --- Household Actions ---
    {"q": "I ___ my teeth now.", "o": ["brush", "am brushing", "is brushing", "brushes"], "c": 1},
    {"q": "He ___ the dishes at the moment.", "o": ["wash", "is washing", "washes", "are washing"], "c": 1},
    {"q": "They ___ the floor.", "o": ["clean", "is cleaning", "are cleaning", "cleans"], "c": 2},
    {"q": "She ___ the plants in the garden.", "o": ["water", "is watering", "waters", "watering"], "c": 1},
    {"q": "We ___ the furniture.", "o": ["dust", "is dusting", "are dusting", "dusts"], "c": 2},
    {"q": "The baby ___ a bottle of milk.", "o": ["drink", "is drinking", "drinks", "are drinking"], "c": 1},
    {"q": "I ___ a shower right now.", "o": ["have", "am having", "is having", "has"], "c": 1},
    {"q": "He ___ his bed.", "o": ["make", "is making", "makes", "are making"], "c": 1},
    {"q": "They ___ their bags for school.", "o": ["pack", "is packing", "are packing", "packs"], "c": 2},
    {"q": "Look! The snow ___.", "o": ["fall", "is falling", "falls", "are falling"], "c": 1},

    # --- Nature & Surroundings ---
    {"q": "The wind ___ very hard today.", "o": ["blow", "is blowing", "blows", "are blowing"], "c": 1},
    {"q": "The leaves ___ from the trees.", "o": ["fall", "is falling", "are falling", "falls"], "c": 2},
    {"q": "The stars ___ in the sky tonight.", "o": ["shine", "is shining", "are shining", "shines"], "c": 2},
    {"q": "The river ___ fast after the rain.", "o": ["flow", "is flowing", "flows", "flowing"], "c": 1},
    {"q": "The moon ___ behind the clouds.", "o": ["hide", "is hiding", "hides", "are hiding"], "c": 1},
    {"q": "Birds ___ a nest in that tree.", "o": ["build", "is building", "are building", "builds"], "c": 2},
    {"q": "It ___ dark outside.", "o": ["get", "is getting", "gets", "are getting"], "c": 1},
    {"q": "The fire ___ in the fireplace.", "o": ["burn", "is burning", "burns", "are burning"], "c": 1},
    {"q": "People ___ under their umbrellas.", "o": ["walk", "is walking", "are walking", "walks"], "c": 2},
    {"q": "The sun ___ down now.", "o": ["go", "is going", "goes", "are going"], "c": 1},

    # --- Modern Life ---
    {"q": "I ___ an interesting article online.", "o": ["read", "am reading", "is reading", "reading"], "c": 1},
    {"q": "He ___ a video on YouTube.", "o": ["watch", "is watching", "watches", "are watching"], "c": 1},
    {"q": "We ___ photos to Instagram.", "o": ["upload", "is uploading", "are uploading", "uploads"], "c": 2},
    {"q": "They ___ a podcast about history.", "o": ["listen", "is listening", "are listening", "listens"], "c": 2},
    {"q": "She ___ her status on Facebook.", "o": ["update", "is updating", "updates", "are updating"], "c": 1},
    {"q": "I ___ a new app on my phone.", "o": ["download", "am downloading", "is downloading", "downloads"], "c": 1},
    {"q": "The battery ___ fast.", "o": ["drain", "is draining", "drains", "are draining"], "c": 1},
    {"q": "We ___ a Zoom meeting right now.", "o": ["have", "is having", "are having", "has"], "c": 2},
    {"q": "They ___ on a new software project.", "o": ["work", "is working", "are working", "works"], "c": 2},
    {"q": "The robot ___ the floor.", "o": ["vacuum", "is vacuuming", "vacuums", "are vacuuming"], "c": 1},

    # --- Transportation & Travel ---
    {"q": "The train ___ into the station now.", "o": ["pull", "is pulling", "pulls", "are pulling"], "c": 1},
    {"q": "We ___ through the mountains.", "o": ["drive", "is driving", "are driving", "drives"], "c": 2},
    {"q": "The plane ___ at the moment.", "o": ["take off", "is taking off", "takes off", "taking"], "c": 1},
    {"q": "They ___ their tickets at the counter.", "o": ["buy", "is buying", "are buying", "buys"], "c": 2},
    {"q": "I ___ my seat on the bus.", "o": ["find", "am finding", "is finding", "finds"], "c": 1},
    {"q": "The ship ___ across the ocean.", "o": ["sail", "is sailing", "sails", "are sailing"], "c": 1},
    {"q": "The traffic ___ very slowly today.", "o": ["move", "is moving", "moves", "are moving"], "c": 1},
    {"q": "We ___ our luggage.", "o": ["carry", "is carrying", "are carrying", "carries"], "c": 2},
    {"q": "The driver ___ the bus.", "o": ["park", "is parking", "parks", "are parking"], "c": 1},
    {"q": "___ you checking in your bags?", "o": ["Is", "Are", "Am", "Do"], "c": 1},

    # --- Beginner Mixed ---
    {"q": "I ___ my lunch.", "o": ["eat", "am eating", "is eating", "eating"], "c": 1},
    {"q": "She ___ on the phone.", "o": ["talk", "is talking", "talks", "are talking"], "c": 1},
    {"q": "They ___ a song.", "o": ["sing", "is singing", "are singing", "sings"], "c": 2},
    {"q": "We ___ in the park.", "o": ["walk", "is walking", "are walking", "walks"], "c": 2},
    {"q": "He ___ his homework.", "o": ["do", "is doing", "does", "are doing"], "c": 1},
    {"q": "Look! The dog ___.", "o": ["jump", "is jumping", "jumps", "are jumping"], "c": 1},
    {"q": "I ___ a book.", "o": ["read", "am reading", "is reading", "reads"], "c": 1},
    {"q": "She ___ a picture.", "o": ["draw", "is drawing", "draws", "are drawing"], "c": 1},
    {"q": "They ___ for you.", "o": ["wait", "is waiting", "are waiting", "waits"], "c": 2},
    {"q": "We ___ tea.", "o": ["drink", "is drinking", "are drinking", "drinks"], "c": 2},
    {"q": "It ___ colder.", "o": ["get", "is getting", "gets", "are getting"], "c": 1},
    {"q": "The baby ___.", "o": ["smile", "is smiling", "smiles", "are smiling"], "c": 1},
    {"q": "I ___ the window.", "o": ["open", "am opening", "is opening", "opens"], "c": 1},
    {"q": "She ___ the door.", "o": ["close", "is closing", "closes", "are closing"], "c": 1},
    {"q": "They ___ to the teacher.", "o": ["listen", "is listening", "are listening", "listens"], "c": 2},

# PRESENT_CONTINUOUS_QUIZ davomi (201 - 300)
    # --- Stative Verbs vs Dynamic (Action) ---
    {"q": "I ___ about buying a new car.", "o": ["think", "am thinking", "thinks", "is thinking"], "c": 1},
    {"q": "The chef ___ the soup to see if it needs salt.", "o": ["tastes", "is tasting", "taste", "are tasting"], "c": 1},
    {"q": "I ___ a great time at the party right now!", "o": ["have", "am having", "has", "is having"], "c": 1},
    {"q": "She ___ the flowers in the garden; they smell lovely.", "o": ["smells", "is smelling", "smell", "are smelling"], "c": 1},
    {"q": "Why ___ you looking at me like that?", "o": ["is", "are", "do", "am"], "c": 1},
    {"q": "I ___ a doctor this afternoon for my check-up.", "o": ["see", "am seeing", "sees", "is seeing"], "c": 1},
    {"q": "The milk ___ sour. I think it's bad.", "o": ["smells", "is smelling", "smell", "are smelling"], "c": 0},
    {"q": "He ___ selfish today, but usually he is kind.", "o": ["is", "is being", "are being", "be"], "c": 1},
    {"q": "They ___ a lot of pressure at work these days.", "o": ["feel", "are feeling", "feels", "is feeling"], "c": 1},
    {"q": "I ___ what you mean now.", "o": ["see", "am seeing", "sees", "is seeing"], "c": 0},

    # --- Business & Work Context ---
    {"q": "We ___ on a new marketing strategy this month.", "o": ["work", "is working", "are working", "works"], "c": 2},
    {"q": "The company ___ its services to Europe.", "o": ["expand", "is expanding", "expands", "are expanding"], "c": 1},
    {"q": "Our team ___ a big conference in Dubai.", "o": ["attend", "is attending", "are attending", "attends"], "c": 2},
    {"q": "I ___ a lot of emails at the moment.", "o": ["send", "am sending", "is sending", "sends"], "c": 1},
    {"q": "The CEO ___ a speech in the hall right now.", "o": ["give", "is giving", "gives", "are giving"], "c": 1},
    {"q": "Sales ___ significantly this quarter.", "o": ["increase", "is increasing", "are increasing", "increases"], "c": 2},
    {"q": "They ___ for the annual report deadline.", "o": ["prepare", "is preparing", "are preparing", "prepares"], "c": 2},
    {"q": "Why ___ the system running so slowly?", "o": ["is", "are", "am", "do"], "c": 0},
    {"q": "We ___ more staff to handle the workload.", "o": ["recruit", "is recruiting", "are recruiting", "recruits"], "c": 2},
    {"q": "I ___ a client in 10 minutes.", "o": ["meet", "am meeting", "meets", "is meeting"], "c": 1},

    # --- Trends & Changing Situations ---
    {"q": "Technology ___ the way we communicate.", "o": ["change", "is changing", "changes", "are changing"], "c": 1},
    {"q": "More people ___ to work from home lately.", "o": ["choose", "is choosing", "are choosing", "chooses"], "c": 2},
    {"q": "The climate ___ warmer every year.", "o": ["get", "is getting", "gets", "are getting"], "c": 1},
    {"q": "Living costs ___ up everywhere.", "o": ["go", "is going", "are going", "goes"], "c": 2},
    {"q": "English ___ more popular in this region.", "o": ["become", "is becoming", "becomes", "are becoming"], "c": 1},
    {"q": "The gap between rich and poor ___.", "o": ["widen", "is widening", "widens", "are widening"], "c": 1},
    {"q": "Social media ___ our mental health.", "o": ["affect", "is affecting", "affects", "are affecting"], "c": 1},
    {"q": "Fresh water ___ scarce in some areas.", "o": ["become", "is becoming", "becomes", "are becoming"], "c": 1},
    {"q": "Traditional shops ___ because of online trade.", "o": ["close", "is closing", "are closing", "closes"], "c": 2},
    {"q": "The world ___ more connected than ever.", "o": ["get", "is getting", "gets", "are getting"], "c": 1},

    # --- Questions with 'Where/Why/How' ---
    {"q": "Where ___ you staying during the trip?", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "Why ___ he acting so strangely?", "o": ["is", "are", "am", "does"], "c": 0},
    {"q": "How ___ your project going?", "o": ["is", "are", "am", "does"], "c": 0},
    {"q": "What ___ they discussing so loudly?", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "Why ___ you laughing? It's not funny!", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "Who ___ she talking to on the phone?", "o": ["is", "are", "am", "do"], "c": 0},
    {"q": "What kind of music ___ you listening to?", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "How many people ___ coming to the wedding?", "o": ["is", "are", "am", "does"], "c": 1},
    {"q": "Where ___ the bus taking us?", "o": ["is", "are", "am", "does"], "c": 0},
    {"q": "Why ___ it getting so cold in here?", "o": ["is", "are", "am", "does"], "c": 0},

    # --- Negative Sentences (isn't/aren't) ---
    {"q": "The heater ___ working properly.", "o": ["isn't", "aren't", "don't", "not"], "c": 0},
    {"q": "I ___ going to the cinema tonight.", "o": ["am not", "isn't", "aren't", "not"], "c": 0},
    {"q": "They ___ paying attention to the signs.", "o": ["isn't", "aren't", "doesn't", "not"], "c": 1},
    {"q": "She ___ feeling very well today.", "o": ["isn't", "aren't", "am not", "not"], "c": 0},
    {"q": "We ___ expecting any visitors.", "o": ["isn't", "aren't", "don't", "not"], "c": 1},
    {"q": "The sun ___ shining today; it's cloudy.", "o": ["isn't", "aren't", "doesn't", "not"], "c": 0},
    {"q": "You ___ making sense right now.", "o": ["isn't", "aren't", "don't", "not"], "c": 1},
    {"q": "My phone ___ charging.", "o": ["isn't", "aren't", "am not", "not"], "c": 0},
    {"q": "The children ___ sleeping yet.", "o": ["isn't", "aren't", "don't", "not"], "c": 1},
    {"q": "He ___ wearing a tie today.", "o": ["isn't", "aren't", "not", "doesn't"], "c": 0},

    # --- Short Answers & Mixed ---
    {"q": "Are you leaving? Yes, I ___.", "o": ["is", "am", "are", "do"], "c": 1},
    {"q": "Is she coming? No, she ___.", "o": ["isn't", "doesn't", "not", "aren't"], "c": 0},
    {"q": "Are they winning? Yes, they ___.", "o": ["is", "are", "do", "am"], "c": 1},
    {"q": "Is the baby crying? No, he ___.", "o": ["isn't", "doesn't", "not", "aren't"], "c": 0},
    {"q": "Am I dreaming? Yes, you ___.", "o": ["is", "am", "are", "do"], "c": 2},
    {"q": "Look! The bridge ___.", "o": ["is opening", "opens", "open", "are opening"], "c": 0},
    {"q": "We ___ a movie tonight. Want to join?", "o": ["watch", "is watching", "are watching", "watches"], "c": 2},
    {"q": "I ___ for my lost wallet.", "o": ["look", "am looking", "is looking", "looking"], "c": 1},
    {"q": "The snow ___ away quickly.", "o": ["melt", "is melting", "melts", "are melting"], "c": 1},
    {"q": "They ___ a surprise party for him.", "o": ["organize", "is organizing", "are organizing", "organizes"], "c": 2},

    # --- Actions at the moment ---
    {"q": "Wait! The light ___ from red to green.", "o": ["change", "is changing", "changes", "are changing"], "c": 1},
    {"q": "I ___ a lot of noise from upstairs.", "o": ["hear", "am hearing", "hears", "is hearing"], "c": 0},
    {"q": "Someone ___ our car!", "o": ["steal", "is stealing", "steals", "are stealing"], "c": 1},
    {"q": "We ___ a video for our school project.", "o": ["film", "is filming", "are filming", "films"], "c": 2},
    {"q": "Look! The leaves ___ red.", "o": ["turn", "is turning", "are turning", "turns"], "c": 2},
    {"q": "I ___ a scarf because it's cold.", "o": ["knit", "am knitting", "is knitting", "knits"], "c": 1},
    {"q": "The cat ___ its fur.", "o": ["clean", "is cleaning", "cleans", "are cleaning"], "c": 1},
    {"q": "They ___ at the funny clown.", "o": ["laugh", "is laughing", "are laughing", "laughs"], "c": 2},
    {"q": "She ___ her luggage to the car.", "o": ["carry", "is carrying", "carries", "are carrying"], "c": 1},
    {"q": "I ___ a delicious cake for your birthday.", "o": ["bake", "am baking", "is baking", "bakes"], "c": 1},

    # --- Future arrangements (Tonight/Tomorrow) ---
    {"q": "We ___ a barbecue on Sunday.", "o": ["have", "is having", "are having", "has"], "c": 2},
    {"q": "I ___ my hair cut tomorrow morning.", "o": ["get", "am getting", "is getting", "gets"], "c": 1},
    {"q": "She ___ her friend at the station.", "o": ["meet", "is meeting", "meets", "meeting"], "c": 1},
    {"q": "They ___ to a new apartment next month.", "o": ["move", "is moving", "are moving", "moves"], "c": 2},
    {"q": "What time ___ the guests arriving?", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "I ___ basketball after school.", "o": ["play", "am playing", "is playing", "plays"], "c": 1},
    {"q": "He ___ for London at 6 PM.", "o": ["leave", "is leaving", "leaves", "leaving"], "c": 1},
    {"q": "We ___ dinner with the Smiths tonight.", "o": ["have", "is having", "are having", "has"], "c": 2},
    {"q": "She ___ a new dress for the ball.", "o": ["buy", "is buying", "buys", "are buying"], "c": 1},
    {"q": "They ___ the house this weekend.", "o": ["clean", "is cleaning", "are cleaning", "cleans"], "c": 2},

    # --- Final Mix ---
    {"q": "Listen! The bells ___.", "o": ["ring", "is ringing", "are ringing", "rings"], "c": 2},
    {"q": "I ___ a shower right now.", "o": ["have", "am having", "is having", "has"], "c": 1},
    {"q": "The baby ___ with the toy.", "o": ["play", "is playing", "plays", "are playing"], "c": 1},
    {"q": "They ___ trees in the park.", "o": ["plant", "is planting", "are planting", "plants"], "c": 2},
    {"q": "We ___ a new song in class.", "o": ["learn", "is learning", "are learning", "learns"], "c": 2},
    {"q": "I ___ to find my glasses.", "o": ["try", "am trying", "is trying", "trying"], "c": 1},
    {"q": "She ___ for the taxi.", "o": ["wait", "is waiting", "waits", "are waiting"], "c": 1},
    {"q": "Look! The plane ___ away.", "o": ["fly", "is flying", "flies", "are flying"], "c": 1},
    {"q": "He ___ some water to drink.", "o": ["pour", "is pouring", "pours", "are pouring"], "c": 1},
    {"q": "We ___ a lot of progress.", "o": ["make", "is making", "are making", "makes"], "c": 2},
    {"q": "I ___ my coffee.", "o": ["stir", "am stirring", "is stirring", "stirs"], "c": 1},
    {"q": "They ___ on the stage.", "o": ["dance", "is dancing", "are dancing", "dances"], "c": 2},
    {"q": "She ___ the vegetables.", "o": ["chop", "is chopping", "chops", "are chopping"], "c": 1},
    {"q": "The sun ___ over the hills.", "o": ["rise", "is rising", "rises", "are rising"], "c": 1},
    {"q": "I ___ my best right now.", "o": ["do", "am doing", "is doing", "doing"], "c": 1},
    {"q": "He ___ for the bus.", "o": ["run", "is running", "runs", "are running"], "c": 1},
    {"q": "They ___ a hole.", "o": ["dig", "is digging", "are digging", "digs"], "c": 2},
    {"q": "We ___ the mountain.", "o": ["climb", "is climbing", "are climbing", "climbs"], "c": 2},
    {"q": "It ___ very dark.", "o": ["get", "is getting", "gets", "are getting"], "c": 1},
    {"q": "I ___ a new car soon.", "o": ["buy", "am buying", "is buying", "buys"], "c": 1},
# PRESENT_CONTINUOUS_QUIZ davomi (301 - 400)
    # --- Everyday Actions & Situations ---
    {"q": "Look! The waiter ___ your coffee.", "o": ["bring", "is bringing", "brings", "are bringing"], "c": 1},
    {"q": "I ___ to solve this math problem.", "o": ["try", "am trying", "is trying", "tries"], "c": 1},
    {"q": "They ___ about the movie right now.", "o": ["talk", "is talking", "are talking", "talks"], "c": 2},
    {"q": "Listen! The wind ___ through the trees.", "o": ["whistle", "is whistling", "whistles", "are whistling"], "c": 1},
    {"q": "She ___ her hair in the bathroom.", "o": ["brush", "is brushing", "brushes", "are brushing"], "c": 1},
    {"q": "We ___ a map to find the museum.", "o": ["use", "is using", "are using", "uses"], "c": 2},
    {"q": "The mechanic ___ my car today.", "o": ["repair", "is repairing", "repairs", "are repairing"], "c": 1},
    {"q": "I ___ for my lost passport everywhere.", "o": ["look", "am looking", "is looking", "looks"], "c": 1},
    {"q": "Look! The squirrel ___ up the wall.", "o": ["run", "is running", "runs", "are running"], "c": 1},
    {"q": "They ___ hands to say goodbye.", "o": ["shake", "is shaking", "are shaking", "shaking"], "c": 2},

    # --- Questions & Grammar Nuances ---
    {"q": "___ you having a good time?", "o": ["Are", "Is", "Am", "Do"], "c": 0},
    {"q": "What ___ that man doing near the gate?", "o": ["is", "are", "am", "does"], "c": 0},
    {"q": "Why ___ everyone looking at us?", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "___ the engine making a strange noise?", "o": ["Is", "Are", "Am", "Does"], "c": 0},
    {"q": "Where ___ the students going now?", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "I ___ not using the computer at the moment.", "o": ["am", "is", "are", "be"], "c": 0},
    {"q": "She ___ not wearing her glasses today.", "o": ["is", "are", "am", "be"], "c": 0},
    {"q": "They ___ not coming to the meeting.", "o": ["is", "are", "am", "be"], "c": 1},
    {"q": "___ I speaking too fast for you?", "o": ["Am", "Is", "Are", "Do"], "c": 0},
    {"q": "Who ___ singing in the shower?", "o": ["is", "are", "am", "does"], "c": 0},

    # --- Future Arrangements ---
    {"q": "I ___ a talk at the university on Tuesday.", "o": ["give", "am giving", "is giving", "gives"], "c": 1},
    {"q": "We ___ at the Italian restaurant at 8:00.", "o": ["meet", "is meeting", "are meeting", "meets"], "c": 2},
    {"q": "She ___ for New York tomorrow night.", "o": ["leave", "is leaving", "leaves", "leaving"], "c": 1},
    {"q": "They ___ a new branch in London next year.", "o": ["open", "is opening", "are opening", "opens"], "c": 2},
    {"q": "What ___ you doing for New Year's Eve?", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "My brother ___ his exam on Friday.", "o": ["take", "is taking", "takes", "taking"], "c": 1},
    {"q": "We ___ a taxi to the airport at 5 AM.", "o": ["take", "is taking", "are taking", "takes"], "c": 2},
    {"q": "I ___ my boss this afternoon.", "o": ["see", "am seeing", "sees", "is seeing"], "c": 1},
    {"q": "The band ___ a concert this weekend.", "o": ["play", "is playing", "plays", "are playing"], "c": 1},
    {"q": "___ they staying with us next week?", "o": ["Is", "Are", "Am", "Do"], "c": 1},

    # --- Trends & Personal Growth ---
    {"q": "More and more people ___ to electric cars.", "o": ["switch", "is switching", "are switching", "switches"], "c": 2},
    {"q": "The city ___ much noisier than before.", "o": ["become", "is becoming", "becomes", "are becoming"], "c": 1},
    {"q": "My health ___ since I started exercising.", "o": ["improve", "is improving", "improves", "are improving"], "c": 1},
    {"q": "Online shopping ___ very popular these days.", "o": ["get", "is getting", "gets", "are getting"], "c": 1},
    {"q": "Computers ___ smaller and more powerful.", "o": ["become", "is becoming", "are becoming", "becomes"], "c": 2},
    {"q": "I ___ to enjoy classical music more.", "o": ["begin", "am beginning", "is beginning", "begins"], "c": 1},
    {"q": "The company ___ a lot of money this year.", "o": ["lose", "is losing", "are losing", "loses"], "c": 2},
    {"q": "Pollution ___ a serious problem.", "o": ["become", "is becoming", "becomes", "are becoming"], "c": 1},
    {"q": "Is your English ___ better?", "o": ["get", "getting", "gets", "to get"], "c": 1},
    {"q": "The sea level ___ slowly.", "o": ["rise", "is rising", "rises", "are rising"], "c": 1},

    # --- Actions with "Always" (Annoyance) ---
    {"q": "You ___ always leaving the lights on!", "o": ["is", "are", "am", "be"], "c": 1},
    {"q": "He ___ always interrupting when I talk.", "o": ["is", "are", "am", "be"], "c": 0},
    {"q": "That dog ___ always barking at nothing.", "o": ["is", "are", "am", "be"], "c": 0},
    {"q": "They ___ always complaining about the food.", "o": ["is", "are", "am", "be"], "c": 1},
    {"q": "I ___ always making the same mistakes.", "o": ["am", "is", "are", "be"], "c": 0},

    # --- Workplace & Projects ---
    {"q": "We ___ a new software update right now.", "o": ["install", "is installing", "are installing", "installs"], "c": 2},
    {"q": "The engineer ___ the bridge's safety.", "o": ["test", "is testing", "tests", "are testing"], "c": 1},
    {"q": "I ___ a report for my manager.", "o": ["write", "am writing", "is writing", "writes"], "c": 1},
    {"q": "They ___ a new office in the city center.", "o": ["build", "is building", "are building", "builds"], "c": 2},
    {"q": "She ___ an interview for the job.", "o": ["have", "is having", "has", "are having"], "c": 1},
    {"q": "The team ___ for the presentation.", "o": ["prepare", "is preparing", "are preparing", "prepares"], "c": 2},
    {"q": "Who ___ the project this week?", "o": ["manage", "is managing", "manages", "are managing"], "c": 1},
    {"q": "I ___ extra hours this month.", "o": ["work", "am working", "is working", "works"], "c": 1},
    {"q": "They ___ the budget for next year.", "o": ["discuss", "is discussing", "are discussing", "discusses"], "c": 2},
    {"q": "The printer ___ the documents now.", "o": ["print", "is printing", "prints", "are printing"], "c": 1},

    # --- Stative/Dynamic Mix ---
    {"q": "I ___ the cake to see if it's ready.", "o": ["taste", "am tasting", "tastes", "is tasting"], "c": 1},
    {"q": "The doctor ___ the patient's pulse.", "o": ["feel", "is feeling", "feels", "are feeling"], "c": 1},
    {"q": "He ___ a very difficult person today.", "o": ["is being", "is", "are being", "be"], "c": 0},
    {"q": "We ___ of moving to a bigger house.", "o": ["think", "is thinking", "are thinking", "thinks"], "c": 2},
    {"q": "She ___ at the old photos.", "o": ["look", "is looking", "looks", "are looking"], "c": 1},

    # --- Travel & Movement ---
    {"q": "The ship ___ into the harbor.", "o": ["sail", "is sailing", "sails", "are sailing"], "c": 1},
    {"q": "I ___ my suitcase for the flight.", "o": ["pack", "am packing", "is packing", "packs"], "c": 1},
    {"q": "They ___ for a hotel near the beach.", "o": ["search", "is searching", "are searching", "searches"], "c": 2},
    {"q": "We ___ through the security check.", "o": ["go", "is going", "are going", "goes"], "c": 2},
    {"q": "The tourists ___ photos of the tower.", "o": ["take", "is taking", "are taking", "takes"], "c": 2},
    {"q": "I ___ on a train to Edinburgh.", "o": ["sit", "am sitting", "is sitting", "sits"], "c": 1},
    {"q": "The bus ___ up the hill slowly.", "o": ["climb", "is climbing", "climbs", "are climbing"], "c": 1},
    {"q": "___ you taking the metro today?", "o": ["Is", "Are", "Am", "Do"], "c": 1},
    {"q": "They ___ their flight status online.", "o": ["check", "is checking", "are checking", "checks"], "c": 2},
    {"q": "The sun ___ behind the mountains.", "o": ["set", "is setting", "sets", "are setting"], "c": 1},

    # --- Household & Family ---
    {"q": "My dad ___ the lawn.", "o": ["mow", "is mowing", "mows", "are mowing"], "c": 1},
    {"q": "The kids ___ a tent in the garden.", "o": ["build", "is building", "are building", "builds"], "c": 2},
    {"q": "I ___ the laundry right now.", "o": ["do", "am doing", "is doing", "does"], "c": 1},
    {"q": "She ___ the table for dinner.", "o": ["set", "is setting", "sets", "are setting"], "c": 1},
    {"q": "They ___ the walls white.", "o": ["paint", "is painting", "are painting", "paints"], "c": 2},
    {"q": "We ___ the old newspapers.", "o": ["recycle", "is recycling", "are recycling", "recycles"], "c": 2},
    {"q": "The cat ___ with a ball of yarn.", "o": ["play", "is playing", "plays", "are playing"], "c": 1},
    {"q": "I ___ a hole in the garden for a tree.", "o": ["dig", "am digging", "is digging", "digs"], "c": 1},
    {"q": "He ___ some juice into a glass.", "o": ["pour", "is pouring", "pours", "are pouring"], "c": 1},
    {"q": "The neighbors ___ a party.", "o": ["have", "is having", "are having", "has"], "c": 2},

    # --- Nature & Weather ---
    {"q": "Look! The ice ___ on the lake.", "o": ["melt", "is melting", "melts", "are melting"], "c": 1},
    {"q": "The leaves ___ yellow and brown.", "o": ["turn", "is turning", "are turning", "turns"], "c": 2},
    {"q": "It ___ heavily outside.", "o": ["snow", "is snowing", "snows", "are snowing"], "c": 1},
    {"q": "The stars ___ brightly tonight.", "o": ["shine", "is shining", "are shining", "shines"], "c": 2},
    {"q": "A cold wind ___ from the north.", "o": ["blow", "is blowing", "blows", "are blowing"], "c": 1},
    {"q": "The water in the pot ___.", "o": ["boil", "is boiling", "boils", "are boiling"], "c": 1},
    {"q": "The sun ___ through the clouds.", "o": ["come", "is coming", "comes", "are coming"], "c": 1},
    {"q": "The flowers ___ in the spring sun.", "o": ["grow", "is growing", "are growing", "grows"], "c": 2},
    {"q": "It ___ dark very early today.", "o": ["get", "is getting", "gets", "are getting"], "c": 1},
    {"q": "The moon ___ tonight.", "o": ["shine", "is shining", "are shining", "shines"], "c": 1},

    # --- Technology & Social Media ---
    {"q": "I ___ a new video for my channel.", "o": ["edit", "am editing", "is editing", "edits"], "c": 1},
    {"q": "They ___ a game on their console.", "o": ["play", "is playing", "are playing", "plays"], "c": 2},
    {"q": "She ___ a comment on my post.", "o": ["write", "is writing", "writes", "writing"], "c": 1},
    {"q": "We ___ our holiday photos.", "o": ["share", "is sharing", "are sharing", "shares"], "c": 2},
    {"q": "The app ___ for updates.", "o": ["search", "is searching", "searches", "are searching"], "c": 1},
    {"q": "I ___ to a new audiobook.", "o": ["listen", "am listening", "is listening", "listens"], "c": 1},
    {"q": "He ___ his phone to the charger.", "o": ["connect", "is connecting", "connects", "are connecting"], "c": 1},
    {"q": "The computer ___ a large file.", "o": ["download", "is downloading", "downloads", "are downloading"], "c": 1},
    {"q": "We ___ a live stream of the launch.", "o": ["watch", "is watching", "are watching", "watches"], "c": 2},
    {"q": "I ___ my password.", "o": ["change", "am changing", "is changing", "changes"], "c": 1},

    # --- Final Rapid Mix ---
    {"q": "Look! The bus ___.", "o": ["come", "is coming", "comes", "are coming"], "c": 1},
    {"q": "Someone ___ at the window!", "o": ["tap", "is tapping", "taps", "are tapping"], "c": 1},
    {"q": "We ___ for our flight now.", "o": ["board", "is boarding", "are boarding", "boards"], "c": 2},
    {"q": "I ___ my tea. It's too cold.", "o": ["not drink", "am not drinking", "is not drinking", "don't drink"], "c": 1},
    {"q": "The baby ___ his first steps.", "o": ["take", "is taking", "takes", "are taking"], "c": 1},
# PRESENT_CONTINUOUS_QUIZ davomi (401 - 500)
    # --- Spelling Focus (Double Consonants & -y endings) ---
    {"q": "The sun ___ over the horizon right now.", "o": ["is seting", "is setting", "sets", "are setting"], "c": 1},
    {"q": "I ___ my suitcase for the trip.", "o": ["am packing", "is packing", "pack", "packing"], "c": 0},
    {"q": "They ___ in the shallow water.", "o": ["is swiming", "are swimming", "swims", "swim"], "c": 1},
    {"q": "Look! The thief ___ away!", "o": ["is runing", "is running", "runs", "are running"], "c": 1},
    {"q": "We ___ a big party for my brother.", "o": ["are planing", "are planning", "plan", "is planning"], "c": 1},
    {"q": "She ___ on the bed because she is tired.", "o": ["is lieing", "is lying", "lies", "are lying"], "c": 1},
    {"q": "The chef ___ the onions into small pieces.", "o": ["is choping", "is chopping", "chops", "are chopping"], "c": 1},
    {"q": "I ___ a hole for the new rose bush.", "o": ["am diging", "am digging", "is digging", "dig"], "c": 1},
    {"q": "The baby ___ with joy.", "o": ["is stoping", "is clapping", "claps", "are clapping"], "c": 1},
    {"q": "They ___ to the radio.", "o": ["is listening", "are listening", "listens", "listening"], "c": 1},

    # --- At the Office / Professional ---
    {"q": "The manager ___ a meeting at the moment.", "o": ["is having", "has", "are having", "having"], "c": 0},
    {"q": "I ___ my emails before I leave.", "o": ["am checking", "check", "is checking", "checks"], "c": 0},
    {"q": "We ___ on a very important contract today.", "o": ["work", "is working", "are working", "works"], "c": 2},
    {"q": "The secretary ___ some documents.", "o": ["is typing", "types", "type", "are typing"], "c": 0},
    {"q": "Why ___ the printer not working?", "o": ["is", "are", "am", "do"], "c": 0},
    {"q": "They ___ the new office furniture now.", "o": ["assemble", "is assembling", "are assembling", "assembles"], "c": 2},
    {"q": "I ___ a presentation for tomorrow's seminar.", "o": ["prepare", "am preparing", "is preparing", "prepares"], "c": 1},
    {"q": "The company ___ more interns this summer.", "o": ["hiring", "is hiring", "hires", "are hiring"], "c": 1},
    {"q": "Who ___ the team while Sarah is on holiday?", "o": ["is leading", "leads", "lead", "are leading"], "c": 0},
    {"q": "We ___ more clients every month.", "o": ["get", "is getting", "are getting", "gets"], "c": 2},

    # --- Feelings and Temporary States ---
    {"q": "I ___ a bit nervous about the interview.", "o": ["feel", "am feeling", "feels", "is feeling"], "c": 1},
    {"q": "Why ___ you being so quiet today?", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "She ___ a lot of pain in her leg.", "o": ["is having", "has", "have", "are having"], "c": 0},
    {"q": "They ___ very kind to us during our stay.", "o": ["is being", "are being", "be", "are"], "c": 1},
    {"q": "I ___ more confident about my English now.", "o": ["feel", "am feeling", "feels", "is feeling"], "c": 1},
    {"q": "The weather ___ colder as we go north.", "o": ["is getting", "gets", "get", "are getting"], "c": 0},
    {"q": "Your skin ___ very red. Are you okay?", "o": ["looks", "is looking", "look", "are looking"], "c": 1},
    {"q": "We ___ a wonderful time at the beach!", "o": ["have", "is having", "are having", "has"], "c": 2},
    {"q": "He ___ more like his father every day.", "o": ["look", "is looking", "looks", "are looking"], "c": 1},
    {"q": "I ___ much better after the medicine.", "o": ["am feeling", "feel", "feels", "is feeling"], "c": 0},

    # --- Specific "Right Now" Actions ---
    {"q": "Look! The cat ___ its milk.", "o": ["is laping", "is lapping", "laps", "are lapping"], "c": 1},
    {"q": "I ___ my tea. It's too hot to drink.", "o": ["am blowing", "blow", "is blowing", "blows"], "c": 0},
    {"q": "Listen! Someone ___ on the drum.", "o": ["is banging", "bang", "bangs", "are banging"], "c": 0},
    {"q": "The kettle ___! I'll make the tea.", "o": ["boils", "is boiling", "boil", "are boiling"], "c": 1},
    {"q": "They ___ hands after the agreement.", "o": ["shake", "is shaking", "are shaking", "shakes"], "c": 2},
    {"q": "I ___ to open this jar, but it's stuck.", "o": ["try", "am trying", "is trying", "trying"], "c": 1},
    {"q": "She ___ for her keys in her handbag.", "o": ["is searching", "search", "searches", "are searching"], "c": 0},
    {"q": "We ___ the bridge right now.", "o": ["cross", "is crossing", "are crossing", "crosses"], "c": 2},
    {"q": "The soldier ___ his boots.", "o": ["is polishing", "polish", "polishes", "are polishing"], "c": 0},
    {"q": "Wait! The light ___ to red.", "o": ["change", "is changing", "changes", "are changing"], "c": 1},

    # --- Future Arrangements (Planned) ---
    {"q": "I ___ my grandparents this weekend.", "o": ["visit", "am visiting", "is visiting", "visits"], "c": 1},
    {"q": "What ___ you cooking for dinner tonight?", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "We ___ a new car next Monday.", "o": ["buy", "is buying", "are buying", "buys"], "c": 2},
    {"q": "She ___ a lecture at the conference.", "o": ["give", "is giving", "gives", "giving"], "c": 1},
    {"q": "They ___ to Spain for their honeymoon.", "o": ["fly", "is flying", "are flying", "flies"], "c": 2},
    {"q": "I ___ lunch with a friend tomorrow.", "o": ["have", "am having", "is having", "has"], "c": 1},
    {"q": "___ you coming to the cinema with us?", "o": ["Are", "Is", "Am", "Do"], "c": 0},
    {"q": "He ___ home for Christmas this year.", "o": ["come", "is coming", "comes", "coming"], "c": 1},
    {"q": "We ___ a test on Tuesday morning.", "o": ["take", "is taking", "are taking", "takes"], "c": 2},
    {"q": "I ___ my hair dyed on Saturday.", "o": ["get", "am getting", "is getting", "gets"], "c": 1},

    # --- Irritating Habits (Always/Constantly) ---
    {"q": "You ___ constantly biting your nails!", "o": ["is", "are", "am", "be"], "c": 1},
    {"q": "He ___ always losing his car keys.", "o": ["is", "are", "am", "be"], "c": 0},
    {"q": "Why ___ you always complaining?", "o": ["is", "are", "am", "do"], "c": 1},
    {"q": "They ___ always making so much noise!", "o": ["is", "are", "am", "be"], "c": 1},
    {"q": "My sister ___ always borrowing my clothes.", "o": ["is", "are", "am", "be"], "c": 0},
    {"q": "I ___ always forgetting people's names.", "o": ["am", "is", "are", "be"], "c": 0},
    {"q": "You ___ always interrupting me!", "o": ["is", "are", "am", "be"], "c": 1},
    {"q": "He ___ always asking for money.", "o": ["is", "are", "am", "be"], "c": 0},
    {"q": "It ___ always raining when I want to go out.", "o": ["is", "are", "am", "be"], "c": 0},
    {"q": "They ___ always telling the same jokes.", "o": ["is", "are", "am", "be"], "c": 1},

    # --- Modern Technology & Trends ---
    {"q": "I ___ my phone's software right now.", "o": ["update", "am updating", "is updating", "updates"], "c": 1},
    {"q": "They ___ a new documentary on Netflix.", "o": ["watch", "is watching", "are watching", "watches"], "c": 2},
    {"q": "She ___ to a podcast about space.", "o": ["listen", "is listening", "are listening", "listens"], "c": 1},
    {"q": "The world's climate ___ rapidly.", "o": ["change", "is changing", "changes", "are changing"], "c": 1},
    {"q": "More people ___ vegan these days.", "o": ["go", "is going", "are going", "goes"], "c": 2},
    {"q": "The battery on my laptop ___ fast.", "o": ["drain", "is draining", "drains", "are draining"], "c": 1},
    {"q": "We ___ a lot of photos to the cloud.", "o": ["upload", "is uploading", "are uploading", "uploads"], "c": 2},
    {"q": "I ___ a message to my group chat.", "o": ["send", "am sending", "is sending", "sends"], "c": 1},
    {"q": "The website ___ very slowly today.", "o": ["load", "is loading", "loads", "are loading"], "c": 1},
    {"q": "Are you ___ the live stream?", "o": ["watch", "watching", "watches", "watched"], "c": 1},

    # --- Household Chores & Daily Life ---
    {"q": "I ___ the vacuuming at the moment.", "o": ["do", "am doing", "is doing", "does"], "c": 1},
    {"q": "My mom ___ the clothes on the line.", "o": ["hang", "is hanging", "hangs", "are hanging"], "c": 1},
    {"q": "We ___ the living room furniture.", "o": ["rearrange", "is rearranging", "are rearranging", "rearranges"], "c": 2},
    {"q": "He ___ the mirrors with a cloth.", "o": ["clean", "is cleaning", "cleans", "are cleaning"], "c": 1},
    {"q": "The cat ___ its claws on the sofa.", "o": ["sharpen", "is sharpening", "sharpens", "are sharpening"], "c": 1},
    {"q": "I ___ the flowers in the vase.", "o": ["arrange", "am arranging", "is arranging", "arranges"], "c": 1},
    {"q": "They ___ the old fence in the yard.", "o": ["fix", "is fixing", "are fixing", "fixes"], "c": 2},
    {"q": "She ___ a delicious soup for lunch.", "o": ["make", "is making", "makes", "are making"], "c": 1},
    {"q": "The baby ___ with the wooden blocks.", "o": ["play", "is playing", "plays", "are playing"], "c": 1},
    {"q": "We ___ our bicycles in the park.", "o": ["ride", "is riding", "are riding", "rides"], "c": 2},

    # --- Sports & Outdoor Activities ---
    {"q": "The runners ___ the final lap now.", "o": ["start", "is starting", "are starting", "starts"], "c": 2},
    {"q": "I ___ for the marathon in October.", "o": ["train", "am training", "is training", "trains"], "c": 1},
    {"q": "He ___ the ball towards the goal.", "o": ["kick", "is kicking", "kicks", "are kicking"], "c": 1},
    {"q": "They ___ a hole for the golf ball.", "o": ["aim", "is aiming", "are aiming", "aims"], "c": 2},
    {"q": "She ___ yoga in the garden.", "o": ["do", "is doing", "does", "doing"], "c": 1},
    {"q": "We ___ down the mountain very fast.", "o": ["ski", "is skiing", "are skiing", "skis"], "c": 2},
    {"q": "The dog ___ after the frisbee.", "o": ["jump", "is jumping", "jumps", "are jumping"], "c": 1},
    {"q": "I ___ my muscles before the race.", "o": ["stretch", "am stretching", "is stretching", "stretches"], "c": 1},
    {"q": "They ___ a campfire near the lake.", "o": ["build", "is building", "are building", "builds"], "c": 2},
    {"q": "The sun ___ down; let's go home.", "o": ["go", "is going", "goes", "are going"], "c": 1},

    # --- Negative Sentences & Final Mix ---
    {"q": "I ___ not feeling very hungry today.", "o": ["am", "is", "are", "be"], "c": 0},
    {"q": "The car ___ starting. Something is wrong.", "o": ["isn't", "aren't", "don't", "not"], "c": 0},
    {"q": "They ___ paying any attention to me.", "o": ["isn't", "aren't", "not", "doesn't"], "c": 1},
    {"q": "She ___ working this Friday.", "o": ["isn't", "aren't", "am not", "not"], "c": 0},
    {"q": "We ___ going anywhere until it stops raining.", "o": ["isn't", "aren't", "don't", "not"], "c": 1},
    {"q": "The heater ___ blowing hot air.", "o": ["isn't", "aren't", "not", "doesn't"], "c": 0},
    {"q": "I ___ listening to that music. Turn it off!", "o": ["am not", "isn't", "aren't", "not"], "c": 0},
    {"q": "You ___ making a very good case.", "o": ["isn't", "aren't", "don't", "not"], "c": 1},
    {"q": "He ___ taking the bus today; he's walking.", "o": ["isn't", "aren't", "not", "doesn't"], "c": 0},
    {"q": "The birds ___ singing today. It's too cold.", "o": ["isn't", "aren't", "don't", "not"], "c": 1}
]
